
import { Category, Language, AppTheme } from "./types";

export const DEFAULT_ROUND_TIME = 60;
export const WINNING_SCORE = 30;
export const ROOM_CODE_LENGTH = 5;
export const JOIN_RETRY_DELAY_MS = 500;
export const BROADCAST_DEBOUNCE_MS = 100;
export const CONNECTION_TIMEOUT_MS = 8000;
export const RECONNECT_INTERVAL_MS = 3000;
export const RECONNECT_MAX_TIME_S = 60;
export const MAX_PLAYERS = 20;
export const ACTION_DEBOUNCE_MS = 250;

export const TEAM_COLORS = [
  { class: 'bg-indigo-500', hex: '#6366f1' },
  { class: 'bg-pink-500', hex: '#ec4899' },
  { class: 'bg-emerald-500', hex: '#10b981' },
  { class: 'bg-yellow-500', hex: '#f59e0b' },
  { class: 'bg-purple-500', hex: '#a855f7' },
  { class: 'bg-blue-500', hex: '#3b82f6' },
  { class: 'bg-orange-500', hex: '#f97316' },
  { class: 'bg-red-500', hex: '#ef4444' },
];

export const MOCK_WORDS: Record<Language, Partial<Record<Category, string[]>>> = {
  [Language.UA]: {
    [Category.GENERAL]: ['Кіт', 'Собака', 'Автомобіль', 'Сонце', 'Море', 'Дерево', 'Будинок', 'Книга', 'Телефон', 'Комп\'ютер', 'Літак', 'Київ', 'Картопля', 'М\'яч', 'Гітара', 'Кава', 'Окуляри', 'Рюкзак', 'Міст', 'Годинник'],
    [Category.FOOD]: ['Яблуко', 'Піца', 'Борщ', 'Кава', 'Шоколад', 'Морозиво', 'Суші', 'Паста', 'Хліб', 'Вино', 'Салат', 'Стейк', 'Лимон', 'Сир', 'Вареники'],
    [Category.TRAVEL]: ['Літак', 'Париж', 'Рюкзак', 'Готель', 'Карта', 'Пляж', 'Гори', 'Поїзд', 'Паспорт', 'Квиток', 'Намет', 'Валіза', 'Музей', 'Компас', 'Океан'],
    [Category.SCIENCE]: ['Атом', 'ДНК', 'Планета', 'Мікроскоп', 'Енергія', 'Робот', 'Космос', 'Формула', 'Лабораторія', 'Генетика', 'Квант', 'Телескоп', 'Магніт', 'Еволюція'],
    [Category.MOVIES]: ['Актор', 'Камера', 'Оскар', 'Сценарій', 'Попкорн', 'Голлівуд', 'Трейлер', 'Режисер', 'Комедія', 'Бойовик', 'Мультфільм', 'Кінотеатр', 'Детектив'],
  },
  [Language.DE]: {
    [Category.GENERAL]: ['Katze', 'Hund', 'Auto', 'Sonne', 'Meer', 'Baum', 'Haus', 'Buch', 'Telefon', 'Computer'],
    [Category.FOOD]: ['Apfel', 'Pizza', 'Borscht', 'Kaffee', 'Schokolade', 'Eis', 'Sushi', 'Pasta', 'Brot', 'Wein'],
    [Category.TRAVEL]: ['Flugzeug', 'Paris', 'Rucksack', 'Hotel', 'Karte', 'Strand', 'Berge', 'Zug', 'Reisepass', 'Ticket'],
    [Category.SCIENCE]: ['Atom', 'DNA', 'Planet', 'Mikroskop', 'Energie', 'Roboter', 'Weltraum', 'Formel', 'Labor', 'Genetik'],
    [Category.MOVIES]: ['Schauspieler', 'Kamera', 'Oscar', 'Drehbuch', 'Popcorn', 'Hollywood', 'Trailer', 'Regisseur', 'Komödie', 'Action'],
  },
  [Language.EN]: {
    [Category.GENERAL]: ['Cat', 'Dog', 'Car', 'Sun', 'Sea', 'Tree', 'House', 'Book', 'Phone', 'Computer'],
    [Category.FOOD]: ['Apple', 'Pizza', 'Borscht', 'Coffee', 'Chocolate', 'Ice Cream', 'Sushi', 'Pasta', 'Bread', 'Wine'],
    [Category.TRAVEL]: ['Airplane', 'Paris', 'Backpack', 'Hotel', 'Map', 'Beach', 'Mountains', 'Train', 'Passport', 'Ticket'],
    [Category.SCIENCE]: ['Atom', 'DNA', 'Planet', 'Microscope', 'Energy', 'Robot', 'Space', 'Formula', 'Laboratory', 'Genetics'],
    [Category.MOVIES]: ['Actor', 'Camera', 'Oscar', 'Script', 'Popcorn', 'Hollywood', 'Trailer', 'Director', 'Comedy', 'Action'],
  },
};

export const TRANSLATIONS: Record<Language, Record<string, any>> = {
  [Language.UA]: {
    slogan: 'Говори швидко, грай яскраво.',
    createGame: 'Створити гру',
    joinGame: 'Приєднатися',
    playOffline: 'Офлайн режим',
    joinTitle: 'Вхід у гру',
    enterCode: 'Введи код кімнати',
    enterCodePlaceholder: '00000',
    enter: 'Увійти',
    whoAreYou: 'Хто ти?',
    namePlaceholder: 'Твій нік',
    chooseAvatar: 'Введи нікнейм та обери аватар',
    next: 'Далі',
    connecting: 'З\'єднання...',
    lobby: 'ЛОБІ',
    roomCode: 'КОД КІМНАТИ',
    players: 'Гравці',
    createTeams: 'Створити команди',
    waitHost: 'Очікуємо хоста...',
    teams: 'Команди',
    shuffle: 'Перемішати',
    startGame: 'Почати гру',
    waitTeams: 'Чекаємо команди...',
    settings: 'Налаштування',
    save: 'Зберегти',
    language: 'Мова',
    theme: 'Тема',
    roundTime: 'Час',
    categories: 'Категорії',
    scoreToWin: 'Перемога при',
    skipPenalty: 'Штраф',
    playingNow: 'Зараз грає',
    explains: 'Пояснює',
    takePhone: 'Бери телефон',
    skip: 'Пропуск',
    correct: 'Вгадано',
    timeIsUp: 'Час вийшов',
    playedTeam: 'Команда: {0}',
    roundPoints: 'Очки',
    continue: 'Далі',
    scoreboard: 'Рахунок',
    nextRound: 'Раунд',
    winners: 'Перемога!',
    playAgain: 'Знову',
    rematch: 'Реванш',
    cancel: 'Відміна',
    playersCount: 'гравців',
    waitAdmin: 'Чекаємо адміна...',
    youGuess: 'Ви відгадуєте',
    sayAloud: 'Кажіть вголос!',
    guessed: 'Вгадано',
    skippedWord: 'Пропущено',
    leaveLobbyConfirm: 'Вийти з лобі?',
    leaveLobbyMsg: 'Ви впевнені, що хочете покинути лобі?',
    rulesTitle: 'Правила',
    rule1: '1. Розділіться на команди.',
    rule2: '2. Пояснюйте слова без спільнокореневих.',
    rule3: '3. Вгадали - свайп вправо (+1).',
    rule4: '4. Не встигли або пропустили - свайп вліво (-1).',
    rule5: '5. Перемагає той, хто швидше набере бали.',
    close: 'Закрити',
    teamNames: ['Ракети', 'Ніндзя', 'Кіберпанки', 'Чемпіони', 'Котики', 'Блискавки', 'Зірки', 'Титани'],
    cat_general: 'Загальне',
    cat_food: 'Їжа',
    cat_travel: 'Подорожі',
    cat_science: 'Наука',
    cat_movies: 'Кіно',
    cat_custom: 'Свої',
    customWords: 'Власні слова',
    customWordsPlaceholder: 'Введіть слова через кому...',
    teamCount: 'Кількість команд',
    sound: 'Звук',
    soundPreset: 'Звукова схема',
    enabled: 'Увімкнено',
    disabled: 'Вимкнено',
    connectionLost: 'З\'єднання втрачено',
    waitingReconnect: 'Очікуємо перепідключення хоста. Відновлюємо сесію...',
    paused: 'ПАУЗА',
    tapResume: 'Натисніть паузу для продовження',
    goal: 'Мета',
    pts: 'оч.',
    points: 'Очки',
    score: 'Рахунок',
    milestone: 'Досягнення',
    teamReached: '{0} досягли {1}!',
    confirmExit: 'Так, вийти',
    confirm: 'Підтвердити',
    goBack: 'Назад',
    connectionFailed: 'Помилка з\'єднання',
    roomNotFound: 'Кімнату {0} не знайдено. Перевірте код.',
    tryAgain: 'Спробувати ще',
    addPlayer: 'Додати гравця',
    removePlayer: 'Видалити',
    playerN: 'Гравець',
    kicked: 'Вас було видалено з гри',
    noPlayersInTeam: 'В команді немає гравців!',
    backToLobby: 'До лобі',
    passPhoneTo: 'Передай телефон — {0}',
    addPlayerTitle: 'Новий гравець',
    add: 'Додати',
    // Info modal sections
    infoRules: 'Правила гри',
    infoModes: 'Режими гри',
    infoLogic: 'Як це працює',
    infoSettings: 'Налаштування',
    infoRule1: 'Один гравець пояснює слово, яке бачить на екрані, своїй команді.',
    infoRule2: 'Не можна використовувати однокореневі слова, переклади та жести.',
    infoRule3: 'Команда намагається вгадати слово за обмежений час.',
    infoRule4: 'Вгадали — натисніть «Вгадано» (+1 бал).',
    infoRule5: 'Не можете пояснити — натисніть «Пропуск» (штраф залежить від налаштувань).',
    infoRule6: 'Коли час закінчується — раунд завершується. Команди грають по черзі. Перша команда, що набере потрібну кількість балів — перемагає!',
    infoOnline: 'Онлайн',
    infoOnlineDesc: 'Створіть кімнату та поділіться кодом або QR-кодом. Кожен гравець грає зі свого телефону. Пояснювач бачить слово на своєму екрані.',
    infoOffline: 'Офлайн',
    infoOfflineDesc: 'Один телефон на всіх. Перед кожним раундом передайте телефон тому, хто пояснює. Слово завжди видно на екрані.',
    infoTurns: 'Команди грають по черзі: Команда 1, потім Команда 2, потім Команда 3 і т.д. Всередині команди гравці також чергуються: спочатку Гравець 1, наступного разу Гравець 2 і т.д.',
    infoExplainer: 'Хто бачить слово?',
    infoExplainerDesc: 'Пояснювач завжди бачить слово та кнопки. Його команда (ті хто вгадують) — не бачать слово. Інші команди бачать слово як спостерігачі, але без кнопок.',
    info1v1: '1 на 1',
    info1v1Desc: 'При 2-3 гравцях кожна команда має 1 гравця. Слово бачить лише той хто пояснює — усі інші вгадують.',
    infoSettingTime: 'Час раунду — тривалість одного раунду (30-180 секунд).',
    infoSettingScore: 'Перемога при — скільки балів потрібно набрати для перемоги.',
    infoSettingCategories: 'Категорії — обирайте теми слів: загальне, їжа, подорожі, наука, кіно або свої слова.',
    infoSettingPenalty: 'Штраф за пропуск — якщо увімкнено, кожен пропуск віднімає 1 бал.',
    infoSettingTeams: 'Кількість команд — від 2 до 10 команд.',
    infoSettingSound: 'Звук — увімкнути або вимкнути звукові ефекти та обрати звукову схему.',
  },
  [Language.DE]: {
    slogan: 'Sprich schnell, spiel hell.',
    createGame: 'Spiel erstellen',
    joinGame: 'Beitreten',
    playOffline: 'Offline-Modus',
    joinTitle: 'Spiel beitreten',
    enterCode: 'Raumcode eingeben',
    enterCodePlaceholder: '00000',
    enter: 'Eintreten',
    whoAreYou: 'Wer bist du?',
    namePlaceholder: 'Dein Name',
    chooseAvatar: 'Name eingeben und Avatar wählen',
    next: 'Weiter',
    connecting: 'Verbinden...',
    lobby: 'LOBBY',
    roomCode: 'RAUMCODE',
    players: 'Spieler',
    createTeams: 'Teams bilden',
    waitHost: 'Warten auf Host...',
    teams: 'Teams',
    shuffle: 'Mischen',
    startGame: 'Starten',
    waitTeams: 'Warten auf Teams...',
    settings: 'Einstellungen',
    save: 'Speichern',
    language: 'Sprache',
    theme: 'Design',
    roundTime: 'Zeit',
    categories: 'Kategorien',
    scoreToWin: 'Sieg bei',
    skipPenalty: 'Strafe',
    playingNow: 'Spielt gerade',
    explains: 'Erklärt',
    takePhone: 'Nimm das Handy',
    skip: 'Weiter',
    correct: 'Richtig',
    timeIsUp: 'Zeit um',
    playedTeam: 'Team: {0}',
    roundPoints: 'Punkte',
    continue: 'Weiter',
    scoreboard: 'Tabelle',
    nextRound: 'Runde',
    winners: 'Gewonnen!',
    playAgain: 'Nochmal',
    rematch: 'Revanche',
    cancel: 'Abbrechen',
    playersCount: 'Spieler',
    waitAdmin: 'Warten auf Admin...',
    youGuess: 'Ihr ratet',
    sayAloud: 'Laut sagen!',
    guessed: 'Richtig',
    skippedWord: 'Übersprungen',
    leaveLobbyConfirm: 'Lobby verlassen?',
    leaveLobbyMsg: 'Sind Sie sicher, dass Sie die Lobby verlassen möchten?',
    rulesTitle: 'Regeln',
    rule1: '1. Teams bilden.',
    rule2: '2. Wörter ohne Stamm erklären.',
    rule3: '3. Richtig - rechts wischen (+1).',
    rule4: '4. Falsch - links wischen (-1).',
    rule5: '5. Wer zuerst die Punkte hat, gewinnt.',
    close: 'Schließen',
    teamNames: ['Raketen', 'Ninjas', 'Cyberpunks', 'Champions', 'Kätzchen', 'Blitze', 'Sterne', 'Titanen'],
    cat_general: 'Allgemein',
    cat_food: 'Essen',
    cat_travel: 'Reisen',
    cat_science: 'Wissenschaft',
    cat_movies: 'Filme',
    cat_custom: 'Eigene',
    customWords: 'Eigene Wörter',
    customWordsPlaceholder: 'Wörter durch Kommas getrennt eingeben...',
    teamCount: 'Teamanzahl',
    sound: 'Ton',
    soundPreset: 'Tonschema',
    enabled: 'Aktiviert',
    disabled: 'Deaktiviert',
    connectionLost: 'Verbindung verloren',
    waitingReconnect: 'Warten auf den Host. Sitzung wird wiederhergestellt...',
    paused: 'PAUSE',
    tapResume: 'Pause erneut drücken zum Fortsetzen',
    goal: 'Ziel',
    pts: 'Pkt.',
    points: 'Punkte',
    score: 'Punktestand',
    milestone: 'Meilenstein',
    teamReached: '{0} erreichte {1}!',
    confirmExit: 'Ja, verlassen',
    confirm: 'Bestätigen',
    goBack: 'Zurück',
    connectionFailed: 'Verbindungsfehler',
    roomNotFound: 'Raum {0} nicht gefunden. Bitte Code prüfen.',
    tryAgain: 'Erneut versuchen',
    addPlayer: 'Spieler hinzufügen',
    removePlayer: 'Entfernen',
    playerN: 'Spieler',
    kicked: 'Sie wurden aus dem Spiel entfernt',
    noPlayersInTeam: 'Keine Spieler im Team!',
    backToLobby: 'Zur Lobby',
    passPhoneTo: 'Gib das Handy — {0}',
    addPlayerTitle: 'Neuer Spieler',
    add: 'Hinzufügen',
    infoRules: 'Spielregeln',
    infoModes: 'Spielmodi',
    infoLogic: 'So funktioniert es',
    infoSettings: 'Einstellungen',
    infoRule1: 'Ein Spieler erklärt das Wort auf dem Bildschirm seinem Team.',
    infoRule2: 'Stammwörter, Übersetzungen und Gesten sind verboten.',
    infoRule3: 'Das Team versucht, das Wort innerhalb der Zeit zu erraten.',
    infoRule4: 'Richtig erraten — tippe auf «Richtig» (+1 Punkt).',
    infoRule5: 'Kann nicht erklären — tippe auf «Weiter» (Strafe je nach Einstellung).',
    infoRule6: 'Wenn die Zeit abläuft, endet die Runde. Teams spielen abwechselnd. Das erste Team mit genug Punkten gewinnt!',
    infoOnline: 'Online',
    infoOnlineDesc: 'Erstelle einen Raum und teile den Code oder QR-Code. Jeder Spieler spielt auf seinem eigenen Handy. Der Erklärer sieht das Wort auf seinem Bildschirm.',
    infoOffline: 'Offline',
    infoOfflineDesc: 'Ein Handy für alle. Vor jeder Runde wird das Handy an den Erklärer weitergegeben. Das Wort ist immer auf dem Bildschirm sichtbar.',
    infoTurns: 'Teams spielen abwechselnd: Team 1, dann Team 2, dann Team 3 usw. Innerhalb eines Teams wechseln sich die Spieler ab: zuerst Spieler 1, dann Spieler 2 usw.',
    infoExplainer: 'Wer sieht das Wort?',
    infoExplainerDesc: 'Der Erklärer sieht immer das Wort und die Tasten. Sein Team (die Rater) sieht das Wort nicht. Andere Teams sehen das Wort als Zuschauer, aber ohne Tasten.',
    info1v1: '1 gegen 1',
    info1v1Desc: 'Bei 2-3 Spielern hat jedes Team 1 Spieler. Nur der Erklärer sieht das Wort — alle anderen raten.',
    infoSettingTime: 'Rundenzeit — Dauer einer Runde (30-180 Sekunden).',
    infoSettingScore: 'Sieg bei — wie viele Punkte zum Gewinnen nötig sind.',
    infoSettingCategories: 'Kategorien — Wortthemen wählen: Allgemein, Essen, Reisen, Wissenschaft, Filme oder eigene Wörter.',
    infoSettingPenalty: 'Strafe für Überspringen — wenn aktiviert, kostet jedes Überspringen 1 Punkt.',
    infoSettingTeams: 'Teamanzahl — von 2 bis 10 Teams.',
    infoSettingSound: 'Ton — Soundeffekte ein/ausschalten und Tonschema wählen.',
  },
  [Language.EN]: {
    slogan: 'Speak fast, play bright.',
    createGame: 'Create Game',
    joinGame: 'Join Game',
    playOffline: 'Offline Mode',
    joinTitle: 'Join Game',
    enterCode: 'Enter room code',
    enterCodePlaceholder: '00000',
    enter: 'Enter',
    whoAreYou: 'Who are you?',
    namePlaceholder: 'Your Nickname',
    chooseAvatar: 'Enter nickname and choose avatar',
    next: 'Next',
    connecting: 'Connecting...',
    lobby: 'LOBBY',
    roomCode: 'ROOM CODE',
    players: 'Players',
    createTeams: 'Create Teams',
    waitHost: 'Waiting for host...',
    teams: 'Teams',
    shuffle: 'Shuffle',
    startGame: 'Start',
    waitTeams: 'Waiting for teams...',
    settings: 'Settings',
    save: 'Save',
    language: 'Language',
    theme: 'Theme',
    roundTime: 'Time',
    categories: 'Categories',
    scoreToWin: 'Win at',
    skipPenalty: 'Penalty',
    playingNow: 'Playing',
    explains: 'Explaining',
    takePhone: 'Take phone',
    skip: 'Skip',
    correct: 'Correct',
    timeIsUp: 'Time\'s up',
    playedTeam: 'Team: {0}',
    roundPoints: 'Points',
    continue: 'Continue',
    scoreboard: 'Scoreboard',
    nextRound: 'Round',
    winners: 'Winners!',
    playAgain: 'Again',
    rematch: 'Rematch',
    cancel: 'Cancel',
    playersCount: 'players',
    waitAdmin: 'Waiting for admin...',
    youGuess: 'You guess',
    sayAloud: 'Say it aloud!',
    guessed: 'Guessed',
    skippedWord: 'Skipped',
    leaveLobbyConfirm: 'Leave lobby?',
    leaveLobbyMsg: 'Are you sure you want to leave the lobby?',
    rulesTitle: 'Rules',
    rule1: '1. Split into teams.',
    rule2: '2. Explain without using the root.',
    rule3: '3. Correct - swipe right (+1).',
    rule4: '4. Skip - swipe left (-1).',
    rule5: '5. First to reach score wins.',
    close: 'Close',
    teamNames: ['Rockets', 'Ninjas', 'Cyberpunks', 'Champions', 'Kittens', 'Thunders', 'Stars', 'Titans'],
    cat_general: 'General',
    cat_food: 'Food',
    cat_travel: 'Travel',
    cat_science: 'Science',
    cat_movies: 'Movies',
    cat_custom: 'Custom',
    customWords: 'Custom Words',
    customWordsPlaceholder: 'Enter words separated by commas...',
    teamCount: 'Team Count',
    sound: 'Sound',
    soundPreset: 'Sound Preset',
    enabled: 'Enabled',
    disabled: 'Disabled',
    connectionLost: 'Connection Lost',
    waitingReconnect: 'Waiting for the host to reconnect. Restoring session...',
    paused: 'PAUSED',
    tapResume: 'Tap pause again to resume',
    goal: 'Goal',
    pts: 'pts',
    points: 'Points',
    score: 'Score',
    milestone: 'Milestone',
    teamReached: '{0} reached {1}!',
    confirmExit: 'Yes, Exit',
    confirm: 'Confirm',
    goBack: 'Go Back',
    connectionFailed: 'Connection Failed',
    roomNotFound: 'Room {0} not found. Please check the code.',
    tryAgain: 'Try Again',
    addPlayer: 'Add Player',
    removePlayer: 'Remove',
    playerN: 'Player',
    kicked: 'You have been removed from the game',
    noPlayersInTeam: 'Team has no players!',
    backToLobby: 'Back to Lobby',
    passPhoneTo: 'Pass the phone — {0}',
    addPlayerTitle: 'New Player',
    add: 'Add',
    infoRules: 'Game Rules',
    infoModes: 'Game Modes',
    infoLogic: 'How It Works',
    infoSettings: 'Settings',
    infoRule1: 'One player explains the word shown on the screen to their team.',
    infoRule2: 'You cannot use root words, translations, or gestures.',
    infoRule3: 'The team tries to guess the word within the time limit.',
    infoRule4: 'Guessed correctly — tap "Correct" (+1 point).',
    infoRule5: 'Can\'t explain — tap "Skip" (penalty depends on settings).',
    infoRule6: 'When time runs out, the round ends. Teams take turns. The first team to reach the target score wins!',
    infoOnline: 'Online',
    infoOnlineDesc: 'Create a room and share the code or QR code. Each player plays on their own phone. The explainer sees the word on their screen.',
    infoOffline: 'Offline',
    infoOfflineDesc: 'One phone for everyone. Pass the phone to the explainer before each round. The word is always visible on screen.',
    infoTurns: 'Teams play in order: Team 1, then Team 2, then Team 3, etc. Within each team, players take turns explaining: first Player 1, next time Player 2, etc.',
    infoExplainer: 'Who sees the word?',
    infoExplainerDesc: 'The explainer always sees the word and buttons. Their team (the guessers) cannot see the word. Other teams can see the word as spectators, but without buttons.',
    info1v1: '1 vs 1',
    info1v1Desc: 'With 2-3 players, each team has 1 player. Only the explainer sees the word — everyone else guesses.',
    infoSettingTime: 'Round Time — duration of each round (30-180 seconds).',
    infoSettingScore: 'Win at — how many points are needed to win.',
    infoSettingCategories: 'Categories — choose word topics: General, Food, Travel, Science, Movies, or custom words.',
    infoSettingPenalty: 'Skip Penalty — if enabled, each skip costs 1 point.',
    infoSettingTeams: 'Team Count — from 2 to 10 teams.',
    infoSettingSound: 'Sound — enable/disable sound effects and choose a sound preset.',
  }
};

export const THEME_CONFIG = {
  [AppTheme.PREMIUM_DARK]: {
    id: AppTheme.PREMIUM_DARK,
    name: 'Premium Dark',
    bg: 'bg-premium-dark-bg',
    card: 'bg-dark-btn-grey border border-white/5 shadow-2xl',
    textMain: 'text-premium-white font-serif',
    textSecondary: 'text-gray-400 font-sans',
    textAccent: 'text-champagne-gold font-sans',
    textGradient: 'text-premium-white font-serif',
    button: 'bg-champagne-gold text-premium-dark-bg hover:bg-champagne-dark font-sans shadow-lg',
    iconColor: 'text-premium-white',
    progressBar: 'bg-champagne-gold',
    isPremium: true
  },
  [AppTheme.PREMIUM_LIGHT]: {
    id: AppTheme.PREMIUM_LIGHT,
    name: 'Premium Light',
    bg: 'bg-slate-50',
    card: 'bg-white border border-slate-200 shadow-xl',
    textMain: 'text-slate-900 font-serif',
    textSecondary: 'text-slate-500 font-sans',
    textAccent: 'text-slate-800 font-sans',
    textGradient: 'text-slate-900 font-serif',
    button: 'bg-slate-900 text-white hover:bg-slate-800 font-sans shadow-md',
    iconColor: 'text-slate-900',
    progressBar: 'bg-slate-900',
    isPremium: true
  },
  [AppTheme.CYBERPUNK]: {
    id: AppTheme.CYBERPUNK,
    name: 'Indigo',
    bg: 'bg-slate-950',
    card: 'bg-slate-900 border border-indigo-500/30 shadow-indigo-500/10',
    textMain: 'text-indigo-100 font-serif',
    textSecondary: 'text-indigo-400 font-sans',
    textAccent: 'text-pink-400 font-sans',
    textGradient: 'text-white font-serif',
    button: 'bg-indigo-600 text-white hover:bg-indigo-500 font-sans',
    iconColor: 'text-indigo-400',
    progressBar: 'bg-indigo-500'
  }
};
