
import { Category, Language, AppTheme } from "./types";

export const DEFAULT_ROUND_TIME = 60;
export const WINNING_SCORE = 30;

export const TEAM_COLORS = [
  { class: 'bg-indigo-500', hex: '#6366f1' },
  { class: 'bg-pink-500', hex: '#ec4899' },
  { class: 'bg-emerald-500', hex: '#10b981' },
  { class: 'bg-yellow-500', hex: '#f59e0b' },
  { class: 'bg-purple-500', hex: '#a855f7' },
  { class: 'bg-blue-500', hex: '#3b82f6' },
  { class: 'bg-orange-500', hex: '#f97316' },
  { class: 'bg-red-500', hex: '#ef4444' },
];

export const MOCK_WORDS: Record<Language, Partial<Record<Category, string[]>>> = {
  [Language.UA]: {
    [Category.GENERAL]: ['Кіт', 'Собака', 'Автомобіль', 'Сонце', 'Море', 'Дерево', 'Будинок', 'Книга', 'Телефон', 'Комп\'ютер'],
    [Category.FOOD]: ['Яблуко', 'Піца', 'Борщ', 'Кава', 'Шоколад', 'Морозиво', 'Суші', 'Паста', 'Хліб', 'Вино'],
    [Category.TRAVEL]: ['Літак', 'Париж', 'Рюкзак', 'Готель', 'Карта', 'Пляж', 'Гори', 'Поїзд', 'Паспорт', 'Квиток'],
    [Category.SCIENCE]: ['Атом', 'ДНК', 'Планета', 'Мікроскоп', 'Енергія', 'Робот', 'Космос', 'Формула', 'Лабораторія', 'Генетика'],
    [Category.MOVIES]: ['Актор', 'Камера', 'Оскар', 'Сценарій', 'Попкорн', 'Голлівуд', 'Трейлер', 'Режисер', 'Комедія', 'Бойовик'],
  },
  [Language.DE]: {
    [Category.GENERAL]: ['Katze', 'Hund', 'Auto', 'Sonne', 'Meer', 'Baum', 'Haus', 'Buch', 'Telefon', 'Computer'],
    [Category.FOOD]: ['Apfel', 'Pizza', 'Borscht', 'Kaffee', 'Schokolade', 'Eis', 'Sushi', 'Pasta', 'Brot', 'Wein'],
    [Category.TRAVEL]: ['Flugzeug', 'Paris', 'Rucksack', 'Hotel', 'Karte', 'Strand', 'Berge', 'Zug', 'Reisepass', 'Ticket'],
    [Category.SCIENCE]: ['Atom', 'DNA', 'Planet', 'Mikroskop', 'Energie', 'Roboter', 'Weltraum', 'Formel', 'Labor', 'Genetik'],
    [Category.MOVIES]: ['Schauspieler', 'Kamera', 'Oscar', 'Drehbuch', 'Popcorn', 'Hollywood', 'Trailer', 'Regisseur', 'Komödie', 'Action'],
  },
  [Language.EN]: {
    [Category.GENERAL]: ['Cat', 'Dog', 'Car', 'Sun', 'Sea', 'Tree', 'House', 'Book', 'Phone', 'Computer'],
    [Category.FOOD]: ['Apple', 'Pizza', 'Borscht', 'Coffee', 'Chocolate', 'Ice Cream', 'Sushi', 'Pasta', 'Bread', 'Wine'],
    [Category.TRAVEL]: ['Airplane', 'Paris', 'Backpack', 'Hotel', 'Map', 'Beach', 'Mountains', 'Train', 'Passport', 'Ticket'],
    [Category.SCIENCE]: ['Atom', 'DNA', 'Planet', 'Microscope', 'Energy', 'Robot', 'Space', 'Formula', 'Laboratory', 'Genetics'],
    [Category.MOVIES]: ['Actor', 'Camera', 'Oscar', 'Script', 'Popcorn', 'Hollywood', 'Trailer', 'Director', 'Comedy', 'Action'],
  },
};

export const TRANSLATIONS = {
  [Language.UA]: {
    slogan: 'Говори швидко, грай яскраво.',
    premiumSlogan: 'PREMIUM COLLECTION',
    createGame: 'Створити гру',
    joinGame: 'Приєднатися',
    playOffline: 'Офлайн режим',
    joinTitle: 'Вхід у гру',
    enterCode: 'Введи код кімнати',
    enterCodePlaceholder: '00000',
    scanQr: 'Сканувати QR',
    or: 'АБО',
    enter: 'Увійти',
    whoAreYou: 'Хто ти?',
    namePlaceholder: 'Твій нік',
    chooseAvatar: 'Введи нікнейм та обери аватар',
    next: 'Далі',
    connecting: 'З\'єднання...',
    lobby: 'ЛОБІ',
    roomCode: 'КОД КІМНАТИ',
    scanToJoin: 'Відскануй, щоб приєднатися',
    players: 'Гравці',
    addBot: 'Додати бота',
    addPlayer: 'Додати гравця',
    createTeams: 'Створити команди',
    minPlayers: 'Потрібно мінімум {0} гравці',
    waitHost: 'Очікуємо, поки хост запустить гру...',
    teams: 'Команди',
    shuffle: 'Перемішати гравців',
    startGame: 'Почати гру',
    waitTeams: 'Зачекайте, поки хост сформує команди...',
    settings: 'Налаштування',
    onlyHostSettings: 'Тільки хост може змінювати налаштування гри.',
    backToLobby: 'Назад в лобі',
    theme: 'Тема оформлення',
    language: 'Мова',
    roundTime: 'Час раунду',
    scoreToWin: 'Балів для перемоги',
    teamCount: 'Кількість команд',
    categories: 'Категорії слів',
    customWords: 'Ваші слова (розділені комою)',
    customWordsPlaceholder: 'Слово1, Слово2, Слово3...',
    skipPenalty: 'Штраф за пропуск (-1)',
    sound: 'Звукові ефекти',
    soundPreset: 'Стиль звуку',
    save: 'Зберегти',
    score: 'Рахунок',
    playingNow: 'Зараз грає',
    explains: 'Пояснює',
    guesses: 'Відгадують',
    takePhone: 'Бере телефон',
    passPhone: 'Передай телефон гравцю:',
    allOthers: 'Всі інші',
    go: 'Поїхали!',
    waitAdmin: 'Очікуємо АДМІНА...',
    onlyExplainerSees: 'Тільки {0} має бачити екран!',
    skip: 'Пропуск',
    correct: 'Є контакт!',
    timeIsUp: 'Час вийшов!',
    playedTeam: 'Грала команда {0}',
    roundPoints: 'Очки за раунд',
    total: 'Всього',
    guessed: 'Вгадано',
    skippedWord: 'Пропуск',
    skippedWordsTitle: 'Пропущені слова',
    noSkips: 'Жодного пропуску! Чудова робота.',
    continue: 'Продовжити',
    scoreboard: 'Таблиця',
    nextRound: 'Наступний раунд',
    winners: 'Переможці!',
    playAgain: 'Нова гра',
    rematch: 'Реванш',
    mvp: 'MVP Гри',
    mostWords: 'пояснив(ла) {0} слів',
    gameOver: 'Гра закінчена',
    getReady: 'Приготуйся...',
    general: 'Загальне',
    control: 'Контроль',
    dontSayRoot: 'Не називай спільнокореневі слова!',
    watchRules: 'Слідкуй за правилами!',
    listenTo: 'Слухайте {0}!',
    youGuess: 'Ви відгадуєте. Час іде...',
    sayAloud: 'Називайте версії вголос!',
    justWatch: 'Спостерігайте за грою.',
    takePhoneAlert: 'Візьми телефон! Ти будеш пояснювати.',
    prepareToGuess: 'Готуйся відгадувати! Ти не побачиш слова.',
    watchGame: 'Слідкуй за грою!',
    rulesTitle: 'Як грати?',
    rulesDesc: 'Прості правила для швидкого старту.',
    rule1: '1. Об\'єднайтеся в команди.',
    rule2: '2. Один гравець пояснює слово, інші відгадують.',
    rule3: '3. Не можна використовувати спільнокореневі слова.',
    rule4: '4. Чим більше слів відгадаєте за час - тим краще.',
    rule5: '5. Перемагає команда з найбільшою кількістю балів.',
    teamNames: ['Ракети', 'Ніндзя', 'Кіберпанки', 'Чемпіони', 'Котики', 'Блискавки', 'Зірки', 'Титани'],
    milestoneReached: 'Новий рубіж!',
    points: 'балів',
    leaveLobbyConfirm: 'Вийти з лобі?',
    leaveLobbyMsg: 'Ви впевнені? Гра буде перервана.',
    leave: 'Вийти',
    cancel: 'Відміна',
    tutorialStep1: 'Створи кімнату або грай на одному телефоні.',
    tutorialStep2: 'Пояснюй слова своїй команді, не називаючи їх прямо.',
    tutorialStep3: 'Свайпай вправо якщо вгадали, вліво - щоб пропустити.',
    tutorialStep4: 'Передай телефон наступному гравцю, коли час вийде!',
    bot: 'Бот',
    admin: 'АДМІН',
    playingStatus: 'ГРАЄ',
    playersCount: 'Гравців',
    nameInput: 'Ім\'я',
    add: 'Додати',
    paused: 'ПАУЗА',
    resume: 'Продовжити',
    copied: 'Скопійовано!',
    close: 'Закрити',
    startBoard: 'СТАРТ',
    finishBoard: 'ФІНІШ',
    cat_general: 'Загальне',
    cat_food: 'Їжа',
    cat_travel: 'Подорожі',
    cat_science: 'Наука',
    cat_movies: 'Кіно',
    cat_custom: 'Свої',
    roomNotFound: 'Кімнату не знайдено. Перевір номер.'
  },
  [Language.DE]: {
    slogan: 'Sprich schnell, spiel hell.',
    premiumSlogan: 'PREMIUM KOLLEKTION',
    createGame: 'Spiel erstellen',
    joinGame: 'Beitreten',
    playOffline: 'Offline-Modus',
    joinTitle: 'Spiel beitreten',
    enterCode: 'Geben Sie den Raumcode ein',
    enterCodePlaceholder: '00000',
    scanQr: 'QR scannen',
    or: 'ODER',
    enter: 'Eintreten',
    whoAreYou: 'Wer bist du?',
    namePlaceholder: 'Dein Name',
    chooseAvatar: 'Name eingeben und Avatar wählen',
    next: 'Weiter',
    connecting: 'Verbinden...',
    lobby: 'LOBBY',
    roomCode: 'RAUMCODE',
    scanToJoin: 'Scannen zum Beitreten',
    players: 'Spieler',
    addBot: 'Bot hinzufügen',
    addPlayer: 'Spieler hinzufügen',
    createTeams: 'Teams bilden',
    minPlayers: 'Mindestens {0} Spieler erforderlich',
    waitHost: 'Warten auf den Host...',
    teams: 'Teams',
    shuffle: 'Mischen',
    startGame: 'Spiel starten',
    waitTeams: 'Warte auf Teambildung...',
    settings: 'Einstellungen',
    onlyHostSettings: 'Nur der Host kann Einstellungen ändern.',
    backToLobby: 'Zurück zur Lobby',
    theme: 'Design',
    language: 'Sprache',
    roundTime: 'Rundenzeit',
    scoreToWin: 'Punkte zum Sieg',
    teamCount: 'Anzahl Teams',
    categories: 'Kategorien',
    customWords: 'Eigene Wörter (kommagetrennt)',
    customWordsPlaceholder: 'Wort1, Wort2, Wort3...',
    skipPenalty: 'Strafe für Überspringen (-1)',
    sound: 'Soundeffekte',
    soundPreset: 'Soundstil',
    save: 'Speichern',
    score: 'Punktestand',
    playingNow: 'Es spielt',
    explains: 'Erklärt',
    guesses: 'Raten',
    takePhone: 'Nimmt das Handy',
    passPhone: 'Gib das Handy an:',
    allOthers: 'Alle anderen',
    go: 'Los geht\'s!',
    waitAdmin: 'Warten auf ADMIN...',
    onlyExplainerSees: 'Nur {0} darf den Bildschirm sehen!',
    skip: 'Weiter',
    correct: 'Richtig!',
    timeIsUp: 'Die Zeit ist um!',
    playedTeam: 'Team {0} hat gespielt',
    roundPoints: 'Rundenpunkte',
    total: 'Gesamt',
    guessed: 'Erraten',
    skippedWord: 'Übersprungen',
    skippedWordsTitle: 'Übersprungene Wörter',
    noSkips: 'Keine Übersprünge! Super Arbeit.',
    continue: 'Weiter',
    scoreboard: 'Tabelle',
    nextRound: 'Nächste Runde',
    winners: 'Gewinner!',
    playAgain: 'Neues Spiel',
    rematch: 'Revanche',
    mvp: 'Spiel MVP',
    mostWords: 'hat {0} Wörter erklärt',
    gameOver: 'Spiel vorbei',
    getReady: 'Mach dich bereit...',
    general: 'Allgemein',
    control: 'Kontrolle',
    dontSayRoot: 'Keine verwandten Wörter nennen!',
    watchRules: 'Regeln beachten!',
    listenTo: 'Hört {0} zu!',
    youGuess: 'Ihr ratet. Die Zeit läuft...',
    sayAloud: 'Sagt die Lösungen laut!',
    justWatch: 'Beobachtet das Spiel.',
    takePhoneAlert: 'Nimm das Handy! Du erklärst.',
    prepareToGuess: 'Mach dich bereit! Du siehst das Wort nicht.',
    watchGame: 'Verfolge das Spiel!',
    rulesTitle: 'Spielregeln',
    rulesDesc: 'Einfache Regeln für einen schnellen Start.',
    rule1: '1. Bildet Teams.',
    rule2: '2. Ein Spieler erklärt, die anderen raten.',
    rule3: '3. Verwende keine Wörter mit demselben Wortstamm.',
    rule4: '4. Je mehr Wörter in der Zeit, desto besser.',
    rule5: '5. Es gewinnt das Team mit den meisten Punkten.',
    teamNames: ['Raketen', 'Ninjas', 'Cyberpunks', 'Champions', 'Kätzchen', 'Blitze', 'Sterne', 'Titanen'],
    milestoneReached: 'Neuer Meilenstein!',
    points: 'Punkte',
    leaveLobbyConfirm: 'Lobby verlassen?',
    leaveLobbyMsg: 'Bist du sicher? Das Spiel wird beendet.',
    leave: 'Verlassen',
    cancel: 'Abbrechen',
    tutorialStep1: 'Erstelle einen Raum oder spiele auf einem Handy.',
    tutorialStep2: 'Erkläre deinem Team Wörter, ohne sie direkt zu nennen.',
    tutorialStep3: 'Wische nach rechts für Richtig, nach links für Überspringen.',
    tutorialStep4: 'Gib das Handy weiter, wenn die Zeit abgelaufen ist!',
    bot: 'Bot',
    admin: 'ADMIN',
    playingStatus: 'SPIELT',
    playersCount: 'Spieler',
    nameInput: 'Name',
    add: 'Hinzufügen',
    paused: 'PAUSE',
    resume: 'Weiter',
    copied: 'Kopiert!',
    close: 'Schließen',
    startBoard: 'START',
    finishBoard: 'ZIEL',
    cat_general: 'Allgemein',
    cat_food: 'Essen',
    cat_travel: 'Reisen',
    cat_science: 'Wissenschaft',
    cat_movies: 'Filme',
    cat_custom: 'Eigene',
    roomNotFound: 'Raum nicht gefunden. Überprüfen Sie die Nummer.'
  },
  [Language.EN]: {
    slogan: 'Speak fast, play bright.',
    premiumSlogan: 'PREMIUM COLLECTION',
    createGame: 'Create Game',
    joinGame: 'Join Game',
    playOffline: 'Offline Mode',
    joinTitle: 'Join Game',
    enterCode: 'Enter room code',
    enterCodePlaceholder: '00000',
    scanQr: 'Scan QR',
    or: 'OR',
    enter: 'Enter',
    whoAreYou: 'Who are you?',
    namePlaceholder: 'Your Nickname',
    chooseAvatar: 'Enter nickname and choose avatar',
    next: 'Next',
    connecting: 'Connecting...',
    lobby: 'LOBBY',
    roomCode: 'ROOM CODE',
    scanToJoin: 'Scan to join',
    players: 'Players',
    addBot: 'Add Bot',
    addPlayer: 'Add Player',
    createTeams: 'Create Teams',
    minPlayers: 'Need at least {0} players',
    waitHost: 'Waiting for host to start...',
    teams: 'Teams',
    shuffle: 'Shuffle Players',
    startGame: 'Start Game',
    waitTeams: 'Wait for host to set up teams...',
    settings: 'Settings',
    onlyHostSettings: 'Only host can change settings.',
    backToLobby: 'Back to Lobby',
    theme: 'Theme',
    language: 'Language',
    roundTime: 'Round Time',
    scoreToWin: 'Score to Win',
    teamCount: 'Number of Teams',
    categories: 'Categories',
    customWords: 'Your Words (comma separated)',
    customWordsPlaceholder: 'Word1, Word2, Word3...',
    skipPenalty: 'Skip Penalty (-1)',
    sound: 'Sound Effects',
    soundPreset: 'Sound Style',
    save: 'Save',
    score: 'Score',
    playingNow: 'Playing Now',
    explains: 'Explaining',
    guesses: 'Guessing',
    takePhone: 'Take the phone',
    passPhone: 'Pass phone to:',
    allOthers: 'Everyone else',
    go: 'Let\'s Go!',
    waitAdmin: 'Waiting for ADMIN...',
    onlyExplainerSees: 'Only {0} should see the screen!',
    skip: 'Skip',
    correct: 'Correct!',
    timeIsUp: 'Time is up!',
    playedTeam: 'Team {0} played',
    roundPoints: 'Round Points',
    total: 'Total',
    guessed: 'Guessed',
    skippedWord: 'Skipped',
    skippedWordsTitle: 'Skipped Words',
    noSkips: 'No skips! Great job.',
    continue: 'Continue',
    scoreboard: 'Scoreboard',
    nextRound: 'Next Round',
    winners: 'Winners!',
    playAgain: 'New Game',
    rematch: 'Rematch',
    mvp: 'Game MVP',
    mostWords: 'explained {0} words',
    gameOver: 'Game Over',
    getReady: 'Get Ready...',
    general: 'General',
    control: 'Control',
    dontSayRoot: 'Don\'t use same-root words!',
    watchRules: 'Watch the rules!',
    listenTo: 'Listen to {0}!',
    youGuess: 'You are guessing. Time is ticking...',
    sayAloud: 'Say guesses aloud!',
    justWatch: 'Just watch the game.',
    takePhoneAlert: 'Take the phone! You are explaining.',
    prepareToGuess: 'Prepare to guess! Don\'t look at the screen.',
    watchGame: 'Watch the game!',
    rulesTitle: 'How to play?',
    rulesDesc: 'Simple rules for a quick start.',
    rule1: '1. Split into teams.',
    rule2: '2. One player explains, others guess.',
    rule3: '3. Do not use words with the same root.',
    rule4: '4. The more words you guess, the better.',
    rule5: '5. The team with the most points wins.',
    teamNames: ['Rockets', 'Ninjas', 'Cyberpunks', 'Champions', 'Kittens', 'Thunders', 'Stars', 'Titans'],
    milestoneReached: 'New Milestone!',
    points: 'points',
    leaveLobbyConfirm: 'Leave Lobby?',
    leaveLobbyMsg: 'Are you sure? The game will be aborted.',
    leave: 'Leave',
    cancel: 'Cancel',
    tutorialStep1: 'Create a room or play offline on one phone.',
    tutorialStep2: 'Explain words to your team without naming them.',
    tutorialStep3: 'Swipe right for correct, left to skip.',
    tutorialStep4: 'Pass the phone to the next player when time is up!',
    bot: 'Bot',
    admin: 'ADMIN',
    playingStatus: 'PLAYING',
    playersCount: 'Players',
    nameInput: 'Name',
    add: 'Add',
    paused: 'PAUSED',
    resume: 'Resume',
    copied: 'Copied!',
    close: 'Close',
    startBoard: 'START',
    finishBoard: 'FINISH',
    cat_general: 'General',
    cat_food: 'Food',
    cat_travel: 'Travel',
    cat_science: 'Science',
    cat_movies: 'Movies',
    cat_custom: 'Custom',
    roomNotFound: 'Room not found. Check the number.'
  }
};

export const THEME_CONFIG = {
  [AppTheme.PREMIUM_DARK]: {
    id: AppTheme.PREMIUM_DARK,
    name: 'Premium Dark',
    bg: 'bg-premium-dark-bg',
    card: 'bg-dark-btn-grey border border-white/5 shadow-2xl',
    textMain: 'text-premium-white font-serif',
    textSecondary: 'text-gray-400 font-sans',
    textAccent: 'text-champagne-gold font-sans',
    textGradient: 'text-premium-white font-serif',
    button: 'bg-champagne-gold text-premium-dark-bg hover:bg-champagne-dark font-sans shadow-lg',
    iconColor: 'text-premium-white',
    progressBar: 'bg-champagne-gold',
    isPremium: true
  },
  [AppTheme.PREMIUM_LIGHT]: {
    id: AppTheme.PREMIUM_LIGHT,
    name: 'Premium Light',
    bg: 'bg-slate-50',
    card: 'bg-white border border-slate-200 shadow-xl',
    textMain: 'text-slate-900 font-serif',
    textSecondary: 'text-slate-500 font-sans',
    textAccent: 'text-slate-800 font-sans',
    textGradient: 'text-slate-900 font-serif',
    button: 'bg-slate-900 text-white hover:bg-slate-800 font-sans shadow-md',
    iconColor: 'text-slate-900',
    progressBar: 'bg-slate-900',
    isPremium: true
  },
  [AppTheme.CYBERPUNK]: {
    id: AppTheme.CYBERPUNK,
    name: 'Indigo',
    bg: 'bg-slate-950',
    card: 'bg-slate-900 border border-indigo-500/30 shadow-indigo-500/10',
    textMain: 'text-indigo-100 font-serif',
    textSecondary: 'text-indigo-400 font-sans',
    textAccent: 'text-pink-400 font-sans',
    textGradient: 'text-white font-serif',
    button: 'bg-indigo-600 text-white hover:bg-indigo-500 font-sans',
    iconColor: 'text-indigo-400',
    progressBar: 'bg-indigo-500'
  }
};
