
import { Category, Language, AppTheme } from "./types";

export const DEFAULT_ROUND_TIME = 60;
export const WINNING_SCORE = 30;
export const ROOM_CODE_LENGTH = 5;
export const JOIN_RETRY_DELAY_MS = 500;
export const BROADCAST_DEBOUNCE_MS = 100;
export const CONNECTION_TIMEOUT_MS = 8000;
export const RECONNECT_INTERVAL_MS = 3000;
export const RECONNECT_MAX_TIME_S = 60;
export const MAX_PLAYERS = 20;
export const ACTION_DEBOUNCE_MS = 250;

export const TEAM_COLORS = [
  { class: 'bg-indigo-500', hex: '#6366f1' },
  { class: 'bg-pink-500', hex: '#ec4899' },
  { class: 'bg-emerald-500', hex: '#10b981' },
  { class: 'bg-yellow-500', hex: '#f59e0b' },
  { class: 'bg-purple-500', hex: '#a855f7' },
  { class: 'bg-blue-500', hex: '#3b82f6' },
  { class: 'bg-orange-500', hex: '#f97316' },
  { class: 'bg-red-500', hex: '#ef4444' },
];

export const MOCK_WORDS: Record<Language, Partial<Record<Category, string[]>>> = {
  [Language.UA]: {
    [Category.GENERAL]: ['Кіт', 'Собака', 'Автомобіль', 'Сонце', 'Море', 'Дерево', 'Будинок', 'Книга', 'Телефон', 'Комп\'ютер', 'Літак', 'Київ', 'Картопля', 'М\'яч', 'Гітара', 'Кава', 'Окуляри', 'Рюкзак', 'Міст', 'Годинник'],
    [Category.FOOD]: ['Яблуко', 'Піца', 'Борщ', 'Кава', 'Шоколад', 'Морозиво', 'Суші', 'Паста', 'Хліб', 'Вино', 'Салат', 'Стейк', 'Лимон', 'Сир', 'Вареники'],
    [Category.TRAVEL]: ['Літак', 'Париж', 'Рюкзак', 'Готель', 'Карта', 'Пляж', 'Гори', 'Поїзд', 'Паспорт', 'Квиток', 'Намет', 'Валіза', 'Музей', 'Компас', 'Океан'],
    [Category.SCIENCE]: ['Атом', 'ДНК', 'Планета', 'Мікроскоп', 'Енергія', 'Робот', 'Космос', 'Формула', 'Лабораторія', 'Генетика', 'Квант', 'Телескоп', 'Магніт', 'Еволюція'],
    [Category.MOVIES]: ['Актор', 'Камера', 'Оскар', 'Сценарій', 'Попкорн', 'Голлівуд', 'Трейлер', 'Режисер', 'Комедія', 'Бойовик', 'Мультфільм', 'Кінотеатр', 'Детектив'],
  },
  [Language.DE]: {
    [Category.GENERAL]: ['Katze', 'Hund', 'Auto', 'Sonne', 'Meer', 'Baum', 'Haus', 'Buch', 'Telefon', 'Computer'],
    [Category.FOOD]: ['Apfel', 'Pizza', 'Borscht', 'Kaffee', 'Schokolade', 'Eis', 'Sushi', 'Pasta', 'Brot', 'Wein'],
    [Category.TRAVEL]: ['Flugzeug', 'Paris', 'Rucksack', 'Hotel', 'Karte', 'Strand', 'Berge', 'Zug', 'Reisepass', 'Ticket'],
    [Category.SCIENCE]: ['Atom', 'DNA', 'Planet', 'Mikroskop', 'Energie', 'Roboter', 'Weltraum', 'Formel', 'Labor', 'Genetik'],
    [Category.MOVIES]: ['Schauspieler', 'Kamera', 'Oscar', 'Drehbuch', 'Popcorn', 'Hollywood', 'Trailer', 'Regisseur', 'Komödie', 'Action'],
  },
  [Language.EN]: {
    [Category.GENERAL]: ['Cat', 'Dog', 'Car', 'Sun', 'Sea', 'Tree', 'House', 'Book', 'Phone', 'Computer'],
    [Category.FOOD]: ['Apple', 'Pizza', 'Borscht', 'Coffee', 'Chocolate', 'Ice Cream', 'Sushi', 'Pasta', 'Bread', 'Wine'],
    [Category.TRAVEL]: ['Airplane', 'Paris', 'Backpack', 'Hotel', 'Map', 'Beach', 'Mountains', 'Train', 'Passport', 'Ticket'],
    [Category.SCIENCE]: ['Atom', 'DNA', 'Planet', 'Microscope', 'Energy', 'Robot', 'Space', 'Formula', 'Laboratory', 'Genetics'],
    [Category.MOVIES]: ['Actor', 'Camera', 'Oscar', 'Script', 'Popcorn', 'Hollywood', 'Trailer', 'Director', 'Comedy', 'Action'],
  },
};

export const TRANSLATIONS = {
  [Language.UA]: {
    slogan: 'Говори швидко, грай яскраво.',
    createGame: 'Створити гру',
    joinGame: 'Приєднатися',
    playOffline: 'Офлайн режим',
    joinTitle: 'Вхід у гру',
    enterCode: 'Введи код кімнати',
    enterCodePlaceholder: '00000',
    enter: 'Увійти',
    whoAreYou: 'Хто ти?',
    namePlaceholder: 'Твій нік',
    chooseAvatar: 'Введи нікнейм та обери аватар',
    next: 'Далі',
    connecting: 'З\'єднання...',
    lobby: 'ЛОБІ',
    roomCode: 'КОД КІМНАТИ',
    players: 'Гравці',
    createTeams: 'Створити команди',
    waitHost: 'Очікуємо хоста...',
    teams: 'Команди',
    shuffle: 'Перемішати',
    startGame: 'Почати гру',
    waitTeams: 'Чекаємо команди...',
    settings: 'Налаштування',
    save: 'Зберегти',
    language: 'Мова',
    theme: 'Тема',
    roundTime: 'Час',
    categories: 'Категорії',
    scoreToWin: 'Перемога при',
    skipPenalty: 'Штраф',
    playingNow: 'Зараз грає',
    explains: 'Пояснює',
    takePhone: 'Бери телефон',
    skip: 'Пропуск',
    correct: 'Вгадано',
    timeIsUp: 'Час вийшов',
    playedTeam: 'Команда: {0}',
    roundPoints: 'Очки',
    continue: 'Далі',
    scoreboard: 'Рахунок',
    nextRound: 'Раунд',
    winners: 'Перемога!',
    playAgain: 'Знову',
    rematch: 'Реванш',
    cancel: 'Відміна',
    playersCount: 'гравців',
    waitAdmin: 'Чекаємо адміна...',
    youGuess: 'Ви відгадуєте',
    sayAloud: 'Кажіть вголос!',
    guessed: 'Вгадано',
    skippedWord: 'Пропущено',
    leaveLobbyConfirm: 'Вийти з лобі?',
    leaveLobbyMsg: 'Ви впевнені, що хочете покинути лобі?',
    rulesTitle: 'Правила',
    rule1: '1. Розділіться на команди.',
    rule2: '2. Пояснюйте слова без спільнокореневих.',
    rule3: '3. Вгадали - свайп вправо (+1).',
    rule4: '4. Не встигли або пропустили - свайп вліво (-1).',
    rule5: '5. Перемагає той, хто швидше набере бали.',
    close: 'Закрити',
    teamNames: ['Ракети', 'Ніндзя', 'Кіберпанки', 'Чемпіони', 'Котики', 'Блискавки', 'Зірки', 'Титани'],
    cat_general: 'Загальне',
    cat_food: 'Їжа',
    cat_travel: 'Подорожі',
    cat_science: 'Наука',
    cat_movies: 'Кіно',
    cat_custom: 'Свої',
    customWords: 'Власні слова',
    customWordsPlaceholder: 'Введіть слова через кому...',
    teamCount: 'Кількість команд',
    sound: 'Звук',
    soundPreset: 'Звукова схема',
    enabled: 'Увімкнено',
    disabled: 'Вимкнено'
  },
  [Language.DE]: {
    slogan: 'Sprich schnell, spiel hell.',
    createGame: 'Spiel erstellen',
    joinGame: 'Beitreten',
    playOffline: 'Offline-Modus',
    joinTitle: 'Spiel beitreten',
    enterCode: 'Raumcode eingeben',
    enterCodePlaceholder: '00000',
    enter: 'Eintreten',
    whoAreYou: 'Wer bist du?',
    namePlaceholder: 'Dein Name',
    chooseAvatar: 'Name eingeben und Avatar wählen',
    next: 'Weiter',
    connecting: 'Verbinden...',
    lobby: 'LOBBY',
    roomCode: 'RAUMCODE',
    players: 'Spieler',
    createTeams: 'Teams bilden',
    waitHost: 'Warten auf Host...',
    teams: 'Teams',
    shuffle: 'Mischen',
    startGame: 'Starten',
    waitTeams: 'Warten на Teams...',
    settings: 'Einstellungen',
    save: 'Speichern',
    language: 'Sprache',
    theme: 'Design',
    roundTime: 'Zeit',
    categories: 'Kategorien',
    scoreToWin: 'Sieg bei',
    skipPenalty: 'Strafe',
    playingNow: 'Spielt gerade',
    explains: 'Erklärt',
    takePhone: 'Nimm das Handy',
    skip: 'Weiter',
    correct: 'Richtig',
    timeIsUp: 'Zeit um',
    playedTeam: 'Team: {0}',
    roundPoints: 'Punkte',
    continue: 'Weiter',
    scoreboard: 'Tabelle',
    nextRound: 'Runde',
    winners: 'Gewonnen!',
    playAgain: 'Nochmal',
    rematch: 'Revanche',
    cancel: 'Abbrechen',
    playersCount: 'Spieler',
    waitAdmin: 'Warten auf Admin...',
    youGuess: 'Ihr ratet',
    sayAloud: 'Laut sagen!',
    guessed: 'Richtig',
    skippedWord: 'Übersprungen',
    leaveLobbyConfirm: 'Lobby verlassen?',
    leaveLobbyMsg: 'Sind Sie sicher, dass Sie die Lobby verlassen möchten?',
    rulesTitle: 'Regeln',
    rule1: '1. Teams bilden.',
    rule2: '2. Wörter ohne Stamm erklären.',
    rule3: '3. Richtig - rechts wischen (+1).',
    rule4: '4. Falsch - links wischen (-1).',
    rule5: '5. Wer zuerst die Punkte hat, gewinnt.',
    close: 'Schließen',
    teamNames: ['Raketen', 'Ninjas', 'Cyberpunks', 'Champions', 'Kätzchen', 'Blitze', 'Sterne', 'Titanen'],
    cat_general: 'Allgemein',
    cat_food: 'Essen',
    cat_travel: 'Reisen',
    cat_science: 'Wissenschaft',
    cat_movies: 'Filme',
    cat_custom: 'Eigene',
    customWords: 'Eigene Wörter',
    customWordsPlaceholder: 'Wörter durch Kommas getrennt eingeben...',
    teamCount: 'Teamanzahl',
    sound: 'Ton',
    soundPreset: 'Tonschema',
    enabled: 'Aktiviert',
    disabled: 'Deaktiviert'
  },
  [Language.EN]: {
    slogan: 'Speak fast, play bright.',
    createGame: 'Create Game',
    joinGame: 'Join Game',
    playOffline: 'Offline Mode',
    joinTitle: 'Join Game',
    enterCode: 'Enter room code',
    enterCodePlaceholder: '00000',
    enter: 'Enter',
    whoAreYou: 'Who are you?',
    namePlaceholder: 'Your Nickname',
    chooseAvatar: 'Enter nickname and choose avatar',
    next: 'Next',
    connecting: 'Connecting...',
    lobby: 'LOBBY',
    roomCode: 'ROOM CODE',
    players: 'Players',
    createTeams: 'Create Teams',
    waitHost: 'Waiting for host...',
    teams: 'Teams',
    shuffle: 'Shuffle',
    startGame: 'Start',
    waitTeams: 'Waiting for teams...',
    settings: 'Settings',
    save: 'Save',
    language: 'Language',
    theme: 'Theme',
    roundTime: 'Time',
    categories: 'Categories',
    scoreToWin: 'Win at',
    skipPenalty: 'Penalty',
    playingNow: 'Playing',
    explains: 'Explaining',
    takePhone: 'Take phone',
    skip: 'Skip',
    correct: 'Correct',
    timeIsUp: 'Time\'s up',
    playedTeam: 'Team: {0}',
    roundPoints: 'Points',
    continue: 'Continue',
    scoreboard: 'Scoreboard',
    nextRound: 'Round',
    winners: 'Winners!',
    playAgain: 'Again',
    rematch: 'Rematch',
    cancel: 'Cancel',
    playersCount: 'players',
    waitAdmin: 'Waiting for admin...',
    youGuess: 'You guess',
    sayAloud: 'Say it aloud!',
    guessed: 'Guessed',
    skippedWord: 'Skipped',
    leaveLobbyConfirm: 'Leave lobby?',
    leaveLobbyMsg: 'Are you sure you want to leave the lobby?',
    rulesTitle: 'Rules',
    rule1: '1. Split into teams.',
    rule2: '2. Explain without using the root.',
    rule3: '3. Correct - swipe right (+1).',
    rule4: '4. Skip - swipe left (-1).',
    rule5: '5. First to reach score wins.',
    close: 'Close',
    teamNames: ['Rockets', 'Ninjas', 'Cyberpunks', 'Champions', 'Kittens', 'Thunders', 'Stars', 'Titans'],
    cat_general: 'General',
    cat_food: 'Food',
    cat_travel: 'Travel',
    cat_science: 'Science',
    cat_movies: 'Movies',
    cat_custom: 'Custom',
    customWords: 'Custom Words',
    customWordsPlaceholder: 'Enter words separated by commas...',
    teamCount: 'Team Count',
    sound: 'Sound',
    soundPreset: 'Sound Preset',
    enabled: 'Enabled',
    disabled: 'Disabled'
  }
};

export const THEME_CONFIG = {
  [AppTheme.PREMIUM_DARK]: {
    id: AppTheme.PREMIUM_DARK,
    name: 'Premium Dark',
    bg: 'bg-premium-dark-bg',
    card: 'bg-dark-btn-grey border border-white/5 shadow-2xl',
    textMain: 'text-premium-white font-serif',
    textSecondary: 'text-gray-400 font-sans',
    textAccent: 'text-champagne-gold font-sans',
    textGradient: 'text-premium-white font-serif',
    button: 'bg-champagne-gold text-premium-dark-bg hover:bg-champagne-dark font-sans shadow-lg',
    iconColor: 'text-premium-white',
    progressBar: 'bg-champagne-gold',
    isPremium: true
  },
  [AppTheme.PREMIUM_LIGHT]: {
    id: AppTheme.PREMIUM_LIGHT,
    name: 'Premium Light',
    bg: 'bg-slate-50',
    card: 'bg-white border border-slate-200 shadow-xl',
    textMain: 'text-slate-900 font-serif',
    textSecondary: 'text-slate-500 font-sans',
    textAccent: 'text-slate-800 font-sans',
    textGradient: 'text-slate-900 font-serif',
    button: 'bg-slate-900 text-white hover:bg-slate-800 font-sans shadow-md',
    iconColor: 'text-slate-900',
    progressBar: 'bg-slate-900',
    isPremium: true
  },
  [AppTheme.CYBERPUNK]: {
    id: AppTheme.CYBERPUNK,
    name: 'Indigo',
    bg: 'bg-slate-950',
    card: 'bg-slate-900 border border-indigo-500/30 shadow-indigo-500/10',
    textMain: 'text-indigo-100 font-serif',
    textSecondary: 'text-indigo-400 font-sans',
    textAccent: 'text-pink-400 font-sans',
    textGradient: 'text-white font-serif',
    button: 'bg-indigo-600 text-white hover:bg-indigo-500 font-sans',
    iconColor: 'text-indigo-400',
    progressBar: 'bg-indigo-500'
  }
};
