// Re-export shared constants
export {
  DEFAULT_ROUND_TIME,
  WINNING_SCORE,
  ROOM_CODE_LENGTH,
  MAX_PLAYERS,
  TEAM_COLORS,
  MOCK_WORDS,
} from '@alias/shared';

import { Language } from '@alias/shared';
import { AppTheme, type ThemeConfig } from './types';

// Client constants
export const ACTION_DEBOUNCE_MS = 250;

export const UI_THEME_IDS = (Object.values(AppTheme) as AppTheme[]).filter(
  (id) => id !== AppTheme.PREMIUM_LIGHT
);

export type TranslationValue = string;
export const TEAM_NAMES: Record<Language, string[]> = {
  [Language.UA]: [
    'Ракети',
    'Ніндзя',
    'Кіберпанки',
    'Чемпіони',
    'Котики',
    'Блискавки',
    'Зірки',
    'Титани',
  ],
  [Language.DE]: [
    'Raketen',
    'Ninjas',
    'Cyberpunks',
    'Champions',
    'Kätzchen',
    'Blitze',
    'Sterne',
    'Titanen',
  ],
  [Language.EN]: [
    'Rockets',
    'Ninjas',
    'Cyberpunks',
    'Champions',
    'Kittens',
    'Thunders',
    'Stars',
    'Titans',
  ],
};

export const TRANSLATIONS: Record<Language, Record<string, TranslationValue>> = {
  [Language.UA]: {
    slogan: 'Говори швидко, грай яскраво.',
    createGame: 'Створити гру',
    joinGame: 'Приєднатися',
    playOffline: 'Офлайн режим',
    joinTitle: 'Вхід у гру',
    enterCode: 'Введи код кімнати',
    enterCodePlaceholder: '00000',
    enter: 'Увійти',
    whoAreYou: 'Хто ти?',
    enterNameRequired: "Введи ім'я",
    namePlaceholder: 'Твій нік',
    chooseAvatar: 'Введи нікнейм та обери аватар',
    next: 'Далі',
    connecting: "З'єднання...",
    lobby: 'ЛОБІ',
    roomCode: 'КОД КІМНАТИ',
    players: 'Гравці',
    createTeams: 'Створити команди',
    waitHost: 'Очікуємо хоста...',
    teams: 'Команди',
    shuffle: 'Перемішати',
    startGame: 'Почати гру',
    vs: 'VS',
    waitTeams: 'Чекаємо команди...',
    settings: 'Налаштування',
    save: 'Зберегти',
    language: 'Мова',
    gameMode: 'Режим гри',
    gameModeClassic: 'Класика',
    gameModeTranslation: 'Переклад',
    gameModeSynonyms: 'Синоніми',
    gameModeQuiz: 'Квіз',
    gameModeHardcore: 'Хардкор',
    gameModeImposter: 'Імпостер',
    gameModeHintClassic: 'Класичний Alias: пояснювач бачить слово, команда вгадує.',
    gameModeHintTranslation:
      'У колоді використовуйте «Слово|Переклад» (власні слова через кому або імпорт словника).',
    gameModeHintQuiz: 'Усі гравці бачать варіанти; хто перший натиснув правильний — +1 команді.',
    gameModeHintSynonyms: 'Поки як класика; окрема логіка колоди синонімів — згодом.',
    gameModeHintHardcore:
      'Як класика, але «Пропуск» одразу завершує раунд пояснювача (без наступного слова).',
    gameModeHintImposter:
      'Один гравець — імпостер. Усі бачать одне слово, імпостер бачить інше (або порожнє). В кінці раунду — обговорення та голосування.',
    targetAnswerLanguage: 'Мова відповіді (підказка для колоди)',
    packLanguage: 'Мова паків',
    packLanguageHint: 'Вибір мови впливає лише на паки/слова, а не на мову інтерфейсу.',
    noPacksForLanguage: 'Немає паків для цієї мови.',
    roundTime: 'Час',
    imposterDiscussionTime: 'Час обговорення',
    categories: 'Категорії',
    scoreToWin: 'Перемога при',
    skipPenalty: 'Штраф',
    playingNow: 'Зараз грає',
    explains: 'Пояснює',
    takePhone: 'Я ГОТОВИЙ',
    skip: 'Пропуск',
    correct: 'Вгадано',
    timeIsUp: 'Час вийшов',
    finishWord: 'Дограйте останнє слово',
    playedTeam: 'Команда: {0}',
    roundPoints: 'Очки',
    continue: 'Далі',
    scoreboard: 'Рахунок',
    nextRound: 'Раунд',
    winners: 'Перемога!',
    playAgain: 'Знову',
    toLobby: 'В лоббі',
    toMainMenu: 'Головне меню',
    rematch: 'Реванш',
    cancel: 'Відміна',
    playersCount: 'гравців',
    waitAdmin: 'Чекаємо адміна...',
    youGuess: 'Ви відгадуєте',
    youExplain: 'Ви пояснюєте',
    sayAloud: 'Кажіть вголос!',
    guesserListenHint: 'Слухайте пояснення!',
    explainHint: 'Поясніть слово не називаючи його!',
    guessed: 'Вгадано',
    skippedWord: 'Пропущено',
    leaveLobbyConfirm: 'Вийти з лобі?',
    leaveLobbyMsg: 'Ви впевнені, що хочете покинути лобі?',
    rulesTitle: 'Правила',
    helpSectionRules: 'Правила',
    helpSectionFaq: 'FAQ',
    helpSectionPrivacy: 'Захист даних',
    helpSectionImpressum: 'Імпресум',
    helpSectionAgb: 'AGB',
    helpRulesQuickTitle: 'Швидкий старт',
    helpRulesModesTitle: 'Режими',
    helpRulesCurrentSettingsTitle: 'Поточні налаштування',
    helpFaqQ1: 'Як почати гру онлайн?',
    helpFaqA1:
      'Створіть кімнату, покажіть код або QR. Кожен гравець приєднується зі свого телефону.',
    helpFaqQ2: 'Як працює офлайн режим?',
    helpFaqA2: 'Один телефон на всіх. Перед раундом передайте телефон пояснювачу.',
    helpFaqQ3: 'Чому “мова паків” не змінює мову інтерфейсу?',
    helpFaqA3:
      'Мова інтерфейсу змінюється в Налаштуваннях додатку. “Мова паків” впливає лише на те, з яких наборів/слів формується гра.',
    helpFaqQ4: 'Чому деякі теми з замочком?',
    helpFaqA4: 'Преміум теми доступні після авторизації в Google.',
    helpPrivacyTitle: 'Захист даних',
    helpPrivacyIntro:
      'Ми збираємо тільки те, що потрібно для входу, синхронізації та роботи гри. Нижче — коротко і по суті.',
    helpPrivacyP1: 'Google Sign-In: отримуємо ID-токен для входу, на сервері видається JWT.',
    helpPrivacyP2:
      'Локально: частина налаштувань і токен можуть зберігатись у localStorage для зручності та авто-відновлення сесії.',
    helpPrivacyP3:
      'Мережа: онлайн-гра працює через Socket.IO, щоб синхронізувати лобі та стан гри між гравцями.',
    helpPrivacyP4:
      'Покупки/помилки: оплати проходять через Stripe; помилки можуть надсилатись у Sentry (якщо ввімкнено).',
    helpImpressumTitle: 'Імпресум',
    helpImpressumBody:
      'ALIAS — веб-додаток для гри в пояснення слів. Якщо ви розгорнули цю інстанцію самостійно — ви є її оператором.',
    helpImpressumHost: 'Поточний хост',
    helpImpressumRepoHint: 'Репозиторій: github.com/pakhadai/ALIAS',
    helpAgbTitle: 'AGB / Умови',
    helpAgbIntro: 'Короткі умови використання для комфортної та чесної гри.',
    helpAgbP1:
      'Гра створена “як є”. Ми не гарантуємо безперебійну роботу в будь-яких мережах/пристроях.',
    helpAgbP2: 'Будь ласка, грайте чесно: не ображайте інших гравців, не спамте і не зривайте гру.',
    helpAgbP3:
      'Не вводьте чутливі дані в нікнейм/кастомні слова — вони можуть бачитися іншим гравцям.',
    helpAgbP4: 'Для преміум-функцій потрібна авторизація; покупки обробляються через Stripe.',
    rule1: '1. Розділіться на команди.',
    rule2: '2. Пояснюйте слова без спільнокореневих.',
    rule3: '3. Вгадали — натисніть «Вгадано» (+1).',
    rule4: '4. Пропустили — натисніть «Пропуск» (-1).',
    rule5: '5. Перемагає той, хто швидше набере бали.',
    close: 'Закрити',
    cat_general: 'Загальне',
    cat_food: 'Їжа',
    cat_travel: 'Подорожі',
    cat_science: 'Наука',
    cat_movies: 'Кіно',
    cat_custom: 'Свої',
    customWords: 'Власні слова',
    customWordsPlaceholder: 'Введіть слова через кому...',
    teamCount: 'Кількість команд',
    teamMode: 'Режим команд',
    teamModeTeams: 'Команди',
    teamModeSolo: 'Кожен за себе',
    teamModeSoloHint: 'У цьому режимі команди вимкнені — кожен гравець грає сам за себе.',
    sound: 'Звук',
    soundPreset: 'Звукова схема',
    vibration: 'Вібрація',
    vibrationHint: 'Вібрація зберігається на цьому пристрої й не впливає на правила лобі.',
    enabled: 'Увімкнено',
    disabled: 'Вимкнено',
    connectionLost: "З'єднання втрачено",
    waitingReconnect: 'Очікуємо перепідключення хоста. Відновлюємо сесію...',
    restoringConnection: "Відновлення з'єднання...",
    enteringRoom: 'Підключення до кімнати…',
    lostServerConnection: "Зв'язок із сервером втрачено. Очікуємо перепідключення...",
    paused: 'ПАУЗА',
    tapResume: 'Натисніть паузу для продовження',
    goal: 'Мета',
    pts: 'оч.',
    points: 'Очки',
    score: 'Рахунок',
    milestone: 'Досягнення',
    teamReached: '{0} досягли {1}!',
    confirmExit: 'Так, вийти',
    confirm: 'Підтвердити',
    goBack: 'Назад',
    connectionFailed: "Помилка з'єднання",
    roomNotFound: 'Кімнату {0} не знайдено. Перевірте код.',
    tryAgain: 'Спробувати ще',
    addPlayer: 'Додати гравця',
    removePlayer: 'Видалити',
    playerN: 'Гравець',
    kicked: 'Вас було видалено з гри',
    playerDisconnected: 'Відключено',
    playerOnlineHint: 'Онлайн',
    kickPlayerTitle: 'Вигнати з кімнати',
    noPlayersInTeam: 'В команді немає гравців!',
    backToLobby: 'До лобі',
    passPhoneTo: 'Передай телефон — {0}',
    addPlayerTitle: 'Новий гравець',
    add: 'Додати',
    // Info modal sections
    infoRules: 'Правила гри',
    infoModes: 'Режими гри',
    infoLogic: 'Як це працює',
    infoSettings: 'Налаштування',
    infoRule1: 'Один гравець пояснює слово, яке бачить на екрані, своїй команді.',
    infoRule2: 'Не можна використовувати однокореневі слова, переклади та жести.',
    infoRule3: 'Команда намагається вгадати слово за обмежений час.',
    infoRule4: 'Вгадали — натисніть «Вгадано» (+1 бал).',
    infoRule5: 'Не можете пояснити — натисніть «Пропуск» (штраф залежить від налаштувань).',
    infoRule6:
      'Коли час закінчується — раунд завершується. Команди грають по черзі. Перша команда, що набере потрібну кількість балів — перемагає!',
    infoOnline: 'Онлайн',
    infoOnlineDesc:
      'Створіть кімнату та поділіться кодом або QR-кодом. Кожен гравець грає зі свого телефону. Пояснювач бачить слово на своєму екрані.',
    infoOffline: 'Офлайн',
    infoOfflineDesc:
      'Один телефон на всіх. Перед кожним раундом передайте телефон тому, хто пояснює. Слово завжди видно на екрані.',
    infoTurns:
      'Команди грають по черзі: Команда 1, потім Команда 2, потім Команда 3 і т.д. Всередині команди гравці також чергуються: спочатку Гравець 1, наступного разу Гравець 2 і т.д.',
    infoExplainer: 'Хто бачить слово?',
    infoExplainerDesc:
      'Пояснювач завжди бачить слово та кнопки. Його команда (ті хто вгадують) — не бачать слово. Інші команди бачать слово як спостерігачі, але без кнопок.',
    info1v1: '1 на 1',
    info1v1Desc:
      'При 2-3 гравцях кожна команда має 1 гравця. Слово бачить лише той хто пояснює — усі інші вгадують.',
    infoSettingTime: 'Час раунду — тривалість одного раунду (30-180 секунд).',
    infoSettingScore: 'Перемога при — скільки балів потрібно набрати для перемоги.',
    infoSettingCategories:
      'Категорії — обирайте тематику слів для гри або використовуйте власні набори.',
    infoSettingPenalty: 'Штраф за пропуск — якщо увімкнено, кожен пропуск віднімає 1 бал.',
    infoSettingTeams: 'Кількість команд — від 2 до 10 команд.',
    topGuessers: 'Кращі гравці',
    guessedStat: 'відгадано',
    finalResults: 'Підсумки гри',
    shareResults: 'Поділитися',
    shareCopied: 'Скопійовано!',
    scanToJoin: 'Відскануйте для приєднання',
    copyRoomCodeTitle: 'Скопіювати код кімнати',
    kickConfirmTitle: 'Вигнати гравця?',
    kickConfirmMsg: 'Точно вигнати {0}?',
    kickConfirmYes: 'Так, вигнати',
    infoSettingSound: 'Звук — увімкнути або вимкнути звукові ефекти та обрати звукову схему.',
    notifications: 'Сповіщення',
    notificationsOn: 'Увімкнено',
    notificationsOff: 'Вимкнено',
    enableNotifications: 'Увімкнути',
    store: 'Магазин',
    myPacks: 'Мої паки',
    pwaUpdateMessage: 'Доступна нова версія гри. Оновити зараз?',
    pwaUpdateReload: 'Оновити',
    pwaUpdateLater: 'Пізніше',
    customDeckDeepLinkSuccess:
      'Словник «{name}» підключено. Він буде використаний при створенні кімнати.',
    customDeckDeepLinkError: 'Не вдалося знайти словник за посиланням.',
    shareDeckLinkCopied: 'Посилання скопійовано!',
    shareDeckLink: 'Поділитися',
    customDeckLobbyLabel: 'Власний словник',
    fullscreenUnavailableTitle: 'Повний екран',
    fullscreenUnavailableBody:
      'У Safari на iPhone сайти не можуть увімкнути справжній повноекран (немає такого API, на відміну від Chrome на комп’ютері). Щоб прибрати адресний рядок і панелі браузера, додайте гру на екран Домів: кнопка «Поділитися» (↑) → «На екран Домів», потім відкривайте з іконки.',
    profileStatsSummary: '{0} ігор · {1} вгадано · {2} пропущено · точність {3}%',
    profileStatsDetailLink: 'Детальна статистика',
    profileStatsCardGames: 'Зіграно',
    profileStatsCardGuessed: 'Вгадано',
    profileStatsCardAccuracy: 'Точність',
    profileTapForDetails: 'Натисніть для деталей',
    profileSectionGame: 'ІГРОВЕ',
    profileSectionSettings: 'НАЛАШТУВАННЯ',
    profileSectionExtra: 'ЕКСТРА',
    profileNavMyStats: 'Моя статистика',
    profileNavMyPacks: 'Мої паки слів',
    profileNavUnlockPacks: 'Відкрити власні паки',
    profileNavUnlockPacksSub: 'Доступно у магазині',
    profileNavProfileSettings: 'Налаштування профілю',
    profileNavLobbySettings: 'Налаштування лоббі',
    profileNavStore: 'Магазин',
    profileLogout: 'ВИЙТИ З АКАУНТУ',
    profileLogoutConfirmTitle: 'Ви впевнені, що хочете вийти?',
    profileLogoutCancel: 'Скасувати',
    profileLogoutConfirm: 'Вийти',
    profileLogoutLoading: 'Вихід...',
    profileAdminPanel: 'Адмін-панель',
    profileAnonymous: 'Анонім',
    profileGuestUser: 'Гість',
    profileFreeAccount: 'БЕЗКОШТОВНИЙ АКАУНТ',
    profilePurchasesTitle: 'Мої покупки',
    profileBenefitsTitle: 'Що ви отримаєте',
    profileBenefitCustomListsLabel: 'Власні словники',
    profileBenefitCustomListsSub: 'Завантажуй свої слова — CSV або текст',
    profileBenefitWordPacksLabel: '{0} паки слів',
    profileBenefitWordPacksLabelZero: 'Паки слів',
    profileBenefitWordPacksSub: 'Нові теми й мови — постійно додаються',
    profileBenefitVisualThemesLabel: '{0} теми',
    profileBenefitVisualThemesLabelZero: 'Теми оформлення',
    profileBenefitVisualThemesSub: 'Унікальний вигляд під ваш стиль',
    profileBenefitGameStatsLabel: 'Статистика',
    profileBenefitGameStatsSub: 'Відстежуй перемоги, раунди та топ-слова',
    profileBenefitSyncLabel: 'Синхронізація',
    profileBenefitSyncSub: 'Покупки й словники на всіх пристроях',
    statsScreenTitle: 'Моя статистика',
    statsRowGamesPlayed: 'Ігор зіграно',
    statsRowWordsGuessed: 'Вгадано слів',
    statsRowWordsSkipped: 'Пропущено',
    statsRowAccuracy: 'Точність',
    statsLastPlayedPrefix: 'Остання гра:',
    statsGuestBannerBody:
      'Увійдіть в акаунт, щоб зберегти свою статистику назавжди та синхронізувати між пристроями.',
    statsGuestBannerCta: 'Увійти',
    themeLockedAuthRequired: 'Доступно лише після авторизації',
    loginTitle: 'Увійдіть в акаунт',
    loginSubtitleShopping: 'Для покупок і збереження прогресу',
    loginSubtitleStats:
      'Зберігайте історію ігор і статистику в акаунті та синхронізуйте їх між пристроями.',
    loginAnonymousNote:
      'Грати можна без реєстрації — авторизація потрібна для покупок і збереження статистики в хмарі',
    loginGoogle: 'Увійти через Google',
    loginGoogleLoading: 'Вхід через Google...',
    loginContinueWithout: 'Продовжити без входу',
    loginGoogleFailed: 'Помилка входу через Google',
    loginGoogleSuppressed:
      'Браузер заблокував спливаюче вікно Google. Спробуйте ще раз або перевірте налаштування браузера.',
  },
  [Language.DE]: {
    slogan: 'Erkläre schnell, spiel brillant.',
    createGame: 'Spiel erstellen',
    joinGame: 'Beitreten',
    playOffline: 'Offline-Modus',
    joinTitle: 'Spiel beitreten',
    enterCode: 'Raumcode eingeben',
    enterCodePlaceholder: '00000',
    enter: 'Eintreten',
    whoAreYou: 'Wer bist du?',
    enterNameRequired: 'Bitte gib deinen Namen ein',
    namePlaceholder: 'Dein Name',
    chooseAvatar: 'Name eingeben und Avatar wählen',
    next: 'Weiter',
    connecting: 'Verbinden...',
    lobby: 'LOBBY',
    roomCode: 'RAUMCODE',
    players: 'Spieler',
    createTeams: 'Teams bilden',
    waitHost: 'Warten auf Host...',
    teams: 'Teams',
    shuffle: 'Mischen',
    startGame: 'Starten',
    vs: 'VS',
    waitTeams: 'Warten auf Teams...',
    settings: 'Einstellungen',
    save: 'Speichern',
    language: 'Sprache',
    gameMode: 'Spielmodus',
    gameModeClassic: 'Klassisch',
    gameModeTranslation: 'Übersetzung',
    gameModeSynonyms: 'Synonyme',
    gameModeQuiz: 'Quiz',
    gameModeHardcore: 'Hardcore',
    gameModeImposter: 'Impostor',
    gameModeHintClassic: 'Klassisches Alias: Erklärer sieht das Wort, Team rät.',
    gameModeHintTranslation: 'Im Deck Format «Wort|Übersetzung» (eigene Wörter oder Import).',
    gameModeHintQuiz: 'Alle sehen Optionen; wer zuerst richtig tippt, +1 fürs Team.',
    gameModeHintSynonyms: 'Vorerst wie Klassik; Synonym-Deck folgt.',
    gameModeHintHardcore:
      'Wie Klassik, aber „Überspringen“ beendet sofort die Erklärrunde (kein nächstes Wort).',
    gameModeHintImposter:
      'Ein Spieler ist der Impostor. Alle sehen ein Wort, der Impostor sieht ein anderes (oder keins). Danach diskutieren und abstimmen.',
    targetAnswerLanguage: 'Antwortsprache (Hinweis)',
    packLanguage: 'Pack-Sprache',
    packLanguageHint: 'Die Sprachwahl beeinflusst nur Packs/Wörter, nicht die UI-Sprache.',
    noPacksForLanguage: 'Keine Packs für diese Sprache.',
    roundTime: 'Zeit',
    imposterDiscussionTime: 'Diskussionszeit',
    categories: 'Kategorien',
    scoreToWin: 'Sieg bei',
    skipPenalty: 'Strafe',
    playingNow: 'Spielt gerade',
    explains: 'Erklärt',
    takePhone: 'ICH BIN BEREIT',
    skip: 'Überspringen',
    correct: 'Richtig',
    timeIsUp: 'Zeit um',
    finishWord: 'Letztes Wort fertig spielen',
    playedTeam: 'Team: {0}',
    roundPoints: 'Punkte',
    continue: 'Weiter',
    scoreboard: 'Tabelle',
    nextRound: 'Runde',
    winners: 'Gewonnen!',
    playAgain: 'Nochmal',
    toLobby: 'Zur Lobby',
    toMainMenu: 'Hauptmenü',
    rematch: 'Revanche',
    cancel: 'Abbrechen',
    playersCount: 'Spieler',
    waitAdmin: 'Warten auf Admin...',
    youGuess: 'Ihr ratet',
    youExplain: 'Ihr erklärt',
    sayAloud: 'Laut sagen!',
    guesserListenHint: 'Hört der Erklärung zu!',
    explainHint: 'Erklärt das Wort ohne es zu nennen!',
    guessed: 'Richtig',
    skippedWord: 'Übersprungen',
    leaveLobbyConfirm: 'Lobby verlassen?',
    leaveLobbyMsg: 'Sind Sie sicher, dass Sie die Lobby verlassen möchten?',
    rulesTitle: 'Regeln',
    helpSectionRules: 'Regeln',
    helpSectionFaq: 'FAQ',
    helpSectionPrivacy: 'Datenschutz',
    helpSectionImpressum: 'Impressum',
    helpSectionAgb: 'AGB',
    helpRulesQuickTitle: 'Schnellstart',
    helpRulesModesTitle: 'Spielmodi',
    helpRulesCurrentSettingsTitle: 'Aktuelle Einstellungen',
    helpFaqQ1: 'Wie starte ich ein Online-Spiel?',
    helpFaqA1: 'Raum erstellen, Code oder QR zeigen. Alle treten vom eigenen Handy bei.',
    helpFaqQ2: 'Wie funktioniert Offline?',
    helpFaqA2: 'Ein Handy für alle. Vor der Runde das Handy an den Erklärer geben.',
    helpFaqQ3: 'Warum ändert “Pack-Sprache” nicht die UI-Sprache?',
    helpFaqA3:
      'Die UI-Sprache wird in den App-Einstellungen geändert. Die Pack-Sprache beeinflusst nur, welche Packs/Wörter genutzt werden.',
    helpFaqQ4: 'Warum sind manche Themes gesperrt?',
    helpFaqA4: 'Premium-Themes sind nach Google-Anmeldung verfügbar.',
    helpPrivacyTitle: 'Datenschutz',
    helpPrivacyIntro:
      'Wir erfassen nur, was für Login, Sync und Spielfunktion nötig ist. Kurz und klar:',
    helpPrivacyP1: 'Google Sign-In: ID-Token fürs Login; der Server gibt ein JWT aus.',
    helpPrivacyP2:
      'Lokal: Einstellungen und Token können im localStorage gespeichert werden (Sitzungs-Wiederherstellung).',
    helpPrivacyP3:
      'Netzwerk: Online-Spiel nutzt Socket.IO zur Synchronisierung von Lobby und Spielzustand.',
    helpPrivacyP4:
      'Käufe/Fehler: Zahlungen über Stripe; Fehlerberichte können an Sentry gehen (falls aktiviert).',
    helpImpressumTitle: 'Impressum',
    helpImpressumBody:
      'ALIAS ist eine Web-App zum Wörter-Erklären. Wenn du diese Instanz selbst betreibst, bist du der Betreiber.',
    helpImpressumHost: 'Aktueller Host',
    helpImpressumRepoHint: 'Repository: github.com/pakhadai/ALIAS',
    helpAgbTitle: 'AGB / Bedingungen',
    helpAgbIntro: 'Kurze Nutzungsbedingungen für faires Spielen.',
    helpAgbP1:
      'Die App wird “wie sie ist” bereitgestellt — ohne Garantie auf ständige Verfügbarkeit.',
    helpAgbP2: 'Bitte fair bleiben: keine Beleidigungen, kein Spam, keine Spielstörung.',
    helpAgbP3:
      'Keine sensiblen Daten in Nickname/Custom-Wörter eingeben — andere können sie sehen.',
    helpAgbP4: 'Premium-Funktionen benötigen Anmeldung; Käufe laufen über Stripe.',
    rule1: '1. Teams bilden.',
    rule2: '2. Wörter ohne Stamm erklären.',
    rule3: '3. Richtig — tippe auf «Richtig» (+1).',
    rule4: '4. Übersprungen — tippe auf «Überspringen» (-1).',
    rule5: '5. Wer zuerst die Punkte hat, gewinnt.',
    close: 'Schließen',
    cat_general: 'Allgemein',
    cat_food: 'Essen',
    cat_travel: 'Reisen',
    cat_science: 'Wissenschaft',
    cat_movies: 'Filme',
    cat_custom: 'Eigene',
    customWords: 'Eigene Wörter',
    customWordsPlaceholder: 'Wörter durch Kommas getrennt eingeben...',
    teamCount: 'Teamanzahl',
    teamMode: 'Teammodus',
    teamModeTeams: 'Teams',
    teamModeSolo: 'Jeder für sich',
    teamModeSoloHint: 'Teams sind deaktiviert — jeder spielt für sich selbst.',
    sound: 'Ton',
    soundPreset: 'Tonschema',
    vibration: 'Vibration',
    vibrationHint:
      'Vibration wird auf diesem Gerät gespeichert und beeinflusst die Lobby-Regeln nicht.',
    enabled: 'Aktiviert',
    disabled: 'Deaktiviert',
    connectionLost: 'Verbindung verloren',
    waitingReconnect: 'Warten auf den Host. Sitzung wird wiederhergestellt...',
    restoringConnection: 'Verbindung wird wiederhergestellt...',
    enteringRoom: 'Raum wird betreten…',
    lostServerConnection: 'Serververbindung getrennt. Warte auf Wiederverbindung...',
    paused: 'PAUSE',
    tapResume: 'Pause erneut drücken zum Fortsetzen',
    goal: 'Ziel',
    pts: 'Pkt.',
    points: 'Punkte',
    score: 'Punktestand',
    milestone: 'Meilenstein',
    teamReached: '{0} erreichte {1}!',
    confirmExit: 'Ja, verlassen',
    confirm: 'Bestätigen',
    goBack: 'Zurück',
    connectionFailed: 'Verbindungsfehler',
    roomNotFound: 'Raum {0} nicht gefunden. Bitte Code prüfen.',
    tryAgain: 'Erneut versuchen',
    addPlayer: 'Spieler hinzufügen',
    removePlayer: 'Entfernen',
    playerN: 'Spieler',
    kicked: 'Sie wurden aus dem Spiel entfernt',
    playerDisconnected: 'Getrennt',
    playerOnlineHint: 'Online',
    kickPlayerTitle: 'Spieler entfernen',
    noPlayersInTeam: 'Keine Spieler im Team!',
    backToLobby: 'Zur Lobby',
    passPhoneTo: 'Gib das Handy — {0}',
    addPlayerTitle: 'Neuer Spieler',
    add: 'Hinzufügen',
    infoRules: 'Spielregeln',
    infoModes: 'Spielmodi',
    infoLogic: 'So funktioniert es',
    infoSettings: 'Einstellungen',
    infoRule1: 'Ein Spieler erklärt das Wort auf dem Bildschirm seinem Team.',
    infoRule2: 'Stammwörter, Übersetzungen und Gesten sind verboten.',
    infoRule3: 'Das Team versucht, das Wort innerhalb der Zeit zu erraten.',
    infoRule4: 'Richtig erraten — tippe auf «Richtig» (+1 Punkt).',
    infoRule5: 'Kann nicht erklären — tippe auf «Überspringen» (Strafe je nach Einstellung).',
    infoRule6:
      'Wenn die Zeit abläuft, endet die Runde. Teams spielen abwechselnd. Das erste Team mit genug Punkten gewinnt!',
    infoOnline: 'Online',
    infoOnlineDesc:
      'Erstelle einen Raum und teile den Code oder QR-Code. Jeder Spieler spielt auf seinem eigenen Handy. Der Erklärer sieht das Wort auf seinem Bildschirm.',
    infoOffline: 'Offline',
    infoOfflineDesc:
      'Ein Handy für alle. Vor jeder Runde wird das Handy an den Erklärer weitergegeben. Das Wort ist immer auf dem Bildschirm sichtbar.',
    infoTurns:
      'Teams spielen abwechselnd: Team 1, dann Team 2, dann Team 3 usw. Innerhalb eines Teams wechseln sich die Spieler ab: zuerst Spieler 1, dann Spieler 2 usw.',
    infoExplainer: 'Wer sieht das Wort?',
    infoExplainerDesc:
      'Der Erklärer sieht immer das Wort und die Tasten. Sein Team (die Rater) sieht das Wort nicht. Andere Teams sehen das Wort als Zuschauer, aber ohne Tasten.',
    info1v1: '1 gegen 1',
    info1v1Desc:
      'Bei 2-3 Spielern hat jedes Team 1 Spieler. Nur der Erklärer sieht das Wort — alle anderen raten.',
    infoSettingTime: 'Rundenzeit — Dauer einer Runde (30-180 Sekunden).',
    infoSettingScore: 'Sieg bei — wie viele Punkte zum Gewinnen nötig sind.',
    infoSettingCategories: 'Kategorien — wähle Themen für die Wörter oder nutze eigene Sets.',
    infoSettingPenalty:
      'Strafe für Überspringen — wenn aktiviert, kostet jedes Überspringen 1 Punkt.',
    infoSettingTeams: 'Teamanzahl — von 2 bis 10 Teams.',
    infoSettingSound: 'Ton — Soundeffekte ein/ausschalten und Tonschema wählen.',
    shareResults: 'Teilen',
    shareCopied: 'Kopiert!',
    scanToJoin: 'Scanne zum Beitreten',
    copyRoomCodeTitle: 'Raumcode kopieren',
    kickConfirmTitle: 'Spieler entfernen?',
    kickConfirmMsg: '{0} wirklich entfernen?',
    kickConfirmYes: 'Ja, entfernen',
    topGuessers: 'Top-Spieler',
    guessedStat: 'erraten',
    finalResults: 'Spielergebnis',
    notifications: 'Benachrichtigungen',
    notificationsOn: 'Aktiviert',
    notificationsOff: 'Deaktiviert',
    enableNotifications: 'Aktivieren',
    store: 'Shop',
    myPacks: 'Meine Packs',
    pwaUpdateMessage: 'Neue Version verfügbar. Jetzt aktualisieren?',
    pwaUpdateReload: 'Aktualisieren',
    pwaUpdateLater: 'Später',
    customDeckDeepLinkSuccess:
      'Kartensatz «{name}» wurde geladen und wird beim Erstellen eines Raums genutzt.',
    customDeckDeepLinkError: 'Kartensatz für diesen Link nicht gefunden.',
    shareDeckLinkCopied: 'Link kopiert!',
    shareDeckLink: 'Teilen',
    customDeckLobbyLabel: 'Eigenes Deck',
    fullscreenUnavailableTitle: 'Vollbild',
    fullscreenUnavailableBody:
      'Safari auf dem iPhone erlaubt Websites keinen programmatischen Vollbildmodus (kein Fullscreen-API wie am Desktop). Tippe auf Teilen (↑) → „Zum Home-Bildschirm“ und öffne das Spiel vom Icon — dann ohne Adressleiste.',
    profileStatsSummary: '{0} Spiele · {1} erraten · {2} übersprungen · {3} % Trefferquote',
    profileStatsDetailLink: 'Detaillierte Statistik',
    profileStatsCardGames: 'Gespielt',
    profileStatsCardGuessed: 'Erraten',
    profileStatsCardAccuracy: 'Trefferquote',
    profileTapForDetails: 'Tippen für Details',
    profileSectionGame: 'SPIEL',
    profileSectionSettings: 'EINSTELLUNGEN',
    profileSectionExtra: 'EXTRA',
    profileNavMyStats: 'Meine Statistik',
    profileNavMyPacks: 'Meine Wortpakete',
    profileNavUnlockPacks: 'Eigene Pakete freischalten',
    profileNavUnlockPacksSub: 'Im Shop verfügbar',
    profileNavProfileSettings: 'Profil-Einstellungen',
    profileNavLobbySettings: 'Lobby-Einstellungen',
    profileNavStore: 'Shop',
    profileLogout: 'ABMELDEN',
    profileLogoutConfirmTitle: 'Möchtest du dich wirklich abmelden?',
    profileLogoutCancel: 'Abbrechen',
    profileLogoutConfirm: 'Abmelden',
    profileLogoutLoading: 'Abmelden...',
    profileAdminPanel: 'Admin-Panel',
    profileAnonymous: 'Anonym',
    profileGuestUser: 'Gast',
    profileFreeAccount: 'KOSTENLOSES KONTO',
    profilePurchasesTitle: 'Meine Käufe',
    profileBenefitsTitle: 'Was du bekommst',
    profileBenefitCustomListsLabel: 'Eigene Wortlisten',
    profileBenefitCustomListsSub: 'Eigene Wörter hochladen — CSV oder Text',
    profileBenefitWordPacksLabel: '{0} Wortpakete',
    profileBenefitWordPacksLabelZero: 'Wortpakete',
    profileBenefitWordPacksSub: 'Neue Themen & Sprachen — wächst ständig',
    profileBenefitVisualThemesLabel: '{0} Designs',
    profileBenefitVisualThemesLabelZero: 'Designs',
    profileBenefitVisualThemesSub: 'Einzigartige Skins für deinen Stil',
    profileBenefitGameStatsLabel: 'Statistiken',
    profileBenefitGameStatsSub: 'Siege, Runden & Top-Wörter verfolgen',
    profileBenefitSyncLabel: 'Synchronisierung',
    profileBenefitSyncSub: 'Käufe & Decks auf allen Geräten',
    statsScreenTitle: 'Meine Statistik',
    statsRowGamesPlayed: 'Gespielte Spiele',
    statsRowWordsGuessed: 'Erratene Wörter',
    statsRowWordsSkipped: 'Übersprungen',
    statsRowAccuracy: 'Trefferquote',
    statsLastPlayedPrefix: 'Zuletzt gespielt:',
    statsGuestBannerBody:
      'Melde dich an, um deine Statistik dauerhaft zu speichern und geräteübergreifend zu synchronisieren.',
    statsGuestBannerCta: 'Anmelden',
    themeLockedAuthRequired: 'Nur nach Anmeldung verfügbar',
    loginTitle: 'Anmelden',
    loginSubtitleShopping: 'Für Käufe und gespeicherten Fortschritt',
    loginSubtitleStats:
      'Speichere Spielverlauf und Statistik in deinem Konto und synchronisiere sie zwischen Geräten.',
    loginAnonymousNote:
      'Spielen geht ohne Registrierung — für Käufe und Cloud-Statistik ist eine Anmeldung nötig',
    loginGoogle: 'Mit Google anmelden',
    loginGoogleLoading: 'Google-Anmeldung...',
    loginContinueWithout: 'Ohne Anmeldung fortfahren',
    loginGoogleFailed: 'Google-Anmeldung fehlgeschlagen',
    loginGoogleSuppressed:
      'Browser hat das Google-Popup blockiert. Versuche es erneut oder überprüfe die Browser-Einstellungen.',
  },
  [Language.EN]: {
    slogan: 'Think fast, play bold.',
    createGame: 'Create Game',
    joinGame: 'Join Game',
    playOffline: 'Offline Mode',
    joinTitle: 'Join Game',
    enterCode: 'Enter room code',
    enterCodePlaceholder: '00000',
    enter: 'Enter',
    whoAreYou: 'Who are you?',
    enterNameRequired: 'Please enter your name',
    namePlaceholder: 'Your Nickname',
    chooseAvatar: 'Enter nickname and choose avatar',
    next: 'Next',
    connecting: 'Connecting...',
    lobby: 'LOBBY',
    roomCode: 'ROOM CODE',
    players: 'Players',
    createTeams: 'Create Teams',
    waitHost: 'Waiting for host...',
    teams: 'Teams',
    shuffle: 'Shuffle',
    startGame: 'Start',
    vs: 'VS',
    waitTeams: 'Waiting for teams...',
    settings: 'Settings',
    save: 'Save',
    language: 'Language',
    gameMode: 'Game mode',
    gameModeClassic: 'Classic',
    gameModeTranslation: 'Translation',
    gameModeSynonyms: 'Synonyms',
    gameModeQuiz: 'Quiz',
    gameModeHardcore: 'Hardcore',
    gameModeImposter: 'Impostor',
    gameModeHintClassic: 'Classic Alias: explainer sees the word, team guesses.',
    gameModeHintTranslation: 'Use «Word|Translation» in the deck (custom words or imported list).',
    gameModeHintQuiz: 'Everyone sees options; first correct tap scores +1 for the team.',
    gameModeHintSynonyms: 'Same as classic for now; dedicated synonym decks later.',
    gameModeHintHardcore:
      'Like classic, but Skip immediately ends the explainer’s turn (no next word).',
    gameModeHintImposter:
      'One player is the impostor. Everyone sees a word, the impostor sees a different one (or none). Then discuss and vote.',
    targetAnswerLanguage: 'Answer language (hint)',
    packLanguage: 'Pack language',
    packLanguageHint: 'This affects packs/words only, not the app UI language.',
    noPacksForLanguage: 'No packs for this language.',
    theme: 'Theme',
    roundTime: 'Time',
    imposterDiscussionTime: 'Discussion time',
    categories: 'Categories',
    scoreToWin: 'Win at',
    skipPenalty: 'Penalty',
    playingNow: 'Playing',
    explains: 'Explaining',
    takePhone: "I'M READY",
    skip: 'Skip',
    correct: 'Correct',
    timeIsUp: "Time's up",
    finishWord: 'Finish the last word',
    playedTeam: 'Team: {0}',
    roundPoints: 'Points',
    continue: 'Continue',
    scoreboard: 'Scoreboard',
    nextRound: 'Round',
    winners: 'Winners!',
    playAgain: 'Again',
    toLobby: 'To Lobby',
    toMainMenu: 'Main Menu',
    rematch: 'Rematch',
    cancel: 'Cancel',
    playersCount: 'players',
    waitAdmin: 'Waiting for admin...',
    youGuess: 'You guess',
    youExplain: 'You explain',
    sayAloud: 'Say it aloud!',
    guesserListenHint: 'Listen to the explanation!',
    explainHint: 'Explain the word without saying it!',
    guessed: 'Guessed',
    skippedWord: 'Skipped',
    leaveLobbyConfirm: 'Leave lobby?',
    leaveLobbyMsg: 'Are you sure you want to leave the lobby?',
    rulesTitle: 'Rules',
    helpSectionRules: 'Rules',
    helpSectionFaq: 'FAQ',
    helpSectionPrivacy: 'Data protection',
    helpSectionImpressum: 'Impressum',
    helpSectionAgb: 'AGB',
    helpRulesQuickTitle: 'Quick start',
    helpRulesModesTitle: 'Modes',
    helpRulesCurrentSettingsTitle: 'Current settings',
    helpFaqQ1: 'How do I start an online game?',
    helpFaqA1: 'Create a room and share the code or QR. Everyone joins from their own phone.',
    helpFaqQ2: 'How does offline mode work?',
    helpFaqA2: 'One phone for everyone. Before each round, pass the phone to the explainer.',
    helpFaqQ3: 'Why doesn’t “Pack language” change the UI language?',
    helpFaqA3:
      'UI language is changed in App Settings. Pack language only affects which packs/words are used in the game.',
    helpFaqQ4: 'Why are some themes locked?',
    helpFaqA4: 'Premium themes are available after Google sign-in.',
    helpPrivacyTitle: 'Data protection',
    helpPrivacyIntro:
      'We only collect what is needed for login, sync, and gameplay. Here’s the short version:',
    helpPrivacyP1: 'Google Sign-In: we receive an ID token; the server issues a JWT.',
    helpPrivacyP2:
      'Local storage: some settings and token may be stored in localStorage for convenience and session restore.',
    helpPrivacyP3:
      'Network: online play uses Socket.IO to synchronize lobby and game state between players.',
    helpPrivacyP4:
      'Purchases/errors: payments are handled by Stripe; error reports may be sent to Sentry (if enabled).',
    helpImpressumTitle: 'Impressum',
    helpImpressumBody:
      'ALIAS is a web app for word-explaining gameplay. If you self-host this instance, you are its operator.',
    helpImpressumHost: 'Current host',
    helpImpressumRepoHint: 'Repository: github.com/pakhadai/ALIAS',
    helpAgbTitle: 'AGB / Terms',
    helpAgbIntro: 'Short terms for a comfortable and fair game.',
    helpAgbP1: 'The app is provided “as is” without guarantees of uninterrupted availability.',
    helpAgbP2: 'Please play fair: no harassment, spam, or deliberate disruption.',
    helpAgbP3: 'Do not put sensitive data into nicknames/custom words — other players may see it.',
    helpAgbP4: 'Premium features require sign-in; purchases are processed via Stripe.',
    rule1: '1. Split into teams.',
    rule2: '2. Explain without using the root.',
    rule3: '3. Guessed — tap "Correct" (+1).',
    rule4: '4. Skip — tap "Skip" (-1).',
    rule5: '5. First to reach score wins.',
    close: 'Close',
    cat_general: 'General',
    cat_food: 'Food',
    cat_travel: 'Travel',
    cat_science: 'Science',
    cat_movies: 'Movies',
    cat_custom: 'Custom',
    customWords: 'Custom Words',
    customWordsPlaceholder: 'Enter words separated by commas...',
    teamCount: 'Team Count',
    teamMode: 'Team mode',
    teamModeTeams: 'Teams',
    teamModeSolo: 'Solo',
    teamModeSoloHint: 'Teams are disabled — each player plays for themselves.',
    sound: 'Sound',
    soundPreset: 'Sound Preset',
    vibration: 'Vibration',
    vibrationHint: "Vibration is stored on this device and won't affect the lobby rules.",
    enabled: 'Enabled',
    disabled: 'Disabled',
    connectionLost: 'Connection Lost',
    waitingReconnect: 'Waiting for the host to reconnect. Restoring session...',
    restoringConnection: 'Restoring connection...',
    enteringRoom: 'Joining the room…',
    lostServerConnection: 'Lost connection to the server. Trying to reconnect...',
    paused: 'PAUSED',
    tapResume: 'Tap pause again to resume',
    goal: 'Goal',
    pts: 'pts',
    points: 'Points',
    score: 'Score',
    milestone: 'Milestone',
    teamReached: '{0} reached {1}!',
    confirmExit: 'Yes, Exit',
    confirm: 'Confirm',
    goBack: 'Go Back',
    connectionFailed: 'Connection Failed',
    roomNotFound: 'Room {0} not found. Please check the code.',
    tryAgain: 'Try Again',
    addPlayer: 'Add Player',
    removePlayer: 'Remove',
    playerN: 'Player',
    kicked: 'You have been removed from the game',
    playerDisconnected: 'Disconnected',
    playerOnlineHint: 'Online',
    kickPlayerTitle: 'Remove player',
    noPlayersInTeam: 'Team has no players!',
    backToLobby: 'Back to Lobby',
    passPhoneTo: 'Pass the phone — {0}',
    addPlayerTitle: 'New Player',
    add: 'Add',
    infoRules: 'Game Rules',
    infoModes: 'Game Modes',
    infoLogic: 'How It Works',
    infoSettings: 'Settings',
    infoRule1: 'One player explains the word shown on the screen to their team.',
    infoRule2: 'You cannot use root words, translations, or gestures.',
    infoRule3: 'The team tries to guess the word within the time limit.',
    infoRule4: 'Guessed correctly — tap "Correct" (+1 point).',
    infoRule5: 'Can\'t explain — tap "Skip" (penalty depends on settings).',
    infoRule6:
      'When time runs out, the round ends. Teams take turns. The first team to reach the target score wins!',
    infoOnline: 'Online',
    infoOnlineDesc:
      'Create a room and share the code or QR code. Each player plays on their own phone. The explainer sees the word on their screen.',
    infoOffline: 'Offline',
    infoOfflineDesc:
      'One phone for everyone. Pass the phone to the explainer before each round. The word is always visible on screen.',
    infoTurns:
      'Teams play in order: Team 1, then Team 2, then Team 3, etc. Within each team, players take turns explaining: first Player 1, next time Player 2, etc.',
    infoExplainer: 'Who sees the word?',
    infoExplainerDesc:
      'The explainer always sees the word and buttons. Their team (the guessers) cannot see the word. Other teams can see the word as spectators, but without buttons.',
    info1v1: '1 vs 1',
    info1v1Desc:
      'With 2-3 players, each team has 1 player. Only the explainer sees the word — everyone else guesses.',
    infoSettingTime: 'Round Time — duration of each round (30-180 seconds).',
    infoSettingScore: 'Win at — how many points are needed to win.',
    infoSettingCategories: 'Categories — choose word topics for the game, or use your own packs.',
    infoSettingPenalty: 'Skip Penalty — if enabled, each skip costs 1 point.',
    infoSettingTeams: 'Team Count — from 2 to 10 teams.',
    infoSettingSound: 'Sound — enable/disable sound effects and choose a sound preset.',
    shareResults: 'Share',
    shareCopied: 'Copied!',
    scanToJoin: 'Scan to join',
    copyRoomCodeTitle: 'Copy room code',
    kickConfirmTitle: 'Kick player?',
    kickConfirmMsg: 'Kick {0}?',
    kickConfirmYes: 'Yes, kick',
    topGuessers: 'Top Guessers',
    guessedStat: 'guessed',
    finalResults: 'Final Results',
    notifications: 'Notifications',
    notificationsOn: 'Enabled',
    notificationsOff: 'Disabled',
    enableNotifications: 'Enable',
    store: 'Store',
    myPacks: 'My Packs',
    pwaUpdateMessage: 'A new version is available. Reload to update?',
    pwaUpdateReload: 'Reload',
    pwaUpdateLater: 'Later',
    customDeckDeepLinkSuccess: 'Deck «{name}» loaded. It will be used when you create a room.',
    customDeckDeepLinkError: 'Could not find a deck for this link.',
    shareDeckLinkCopied: 'Link copied!',
    shareDeckLink: 'Share',
    customDeckLobbyLabel: 'Custom deck',
    fullscreenUnavailableTitle: 'Fullscreen',
    fullscreenUnavailableBody:
      'iPhone Safari does not support true fullscreen for websites (no Fullscreen API like desktop Chrome). Tap Share (↑) → Add to Home Screen, then open the game from the icon to hide the address bar.',
    profileStatsSummary: '{0} games · {1} guessed · {2} skipped · {3}% accuracy',
    profileStatsDetailLink: 'Detailed statistics',
    profileStatsCardGames: 'Played',
    profileStatsCardGuessed: 'Guessed',
    profileStatsCardAccuracy: 'Accuracy',
    profileTapForDetails: 'Tap for details',
    profileSectionGame: 'GAME',
    profileSectionSettings: 'SETTINGS',
    profileSectionExtra: 'EXTRA',
    profileNavMyStats: 'My statistics',
    profileNavMyPacks: 'My word packs',
    profileNavUnlockPacks: 'Unlock custom packs',
    profileNavUnlockPacksSub: 'Available in the store',
    profileNavProfileSettings: 'Profile settings',
    profileNavLobbySettings: 'Lobby settings',
    profileNavStore: 'Store',
    profileLogout: 'LOG OUT',
    profileLogoutConfirmTitle: 'Are you sure you want to log out?',
    profileLogoutCancel: 'Cancel',
    profileLogoutConfirm: 'Log out',
    profileLogoutLoading: 'Logging out...',
    profileAdminPanel: 'Admin panel',
    profileAnonymous: 'Anonymous',
    profileGuestUser: 'Guest user',
    profileFreeAccount: 'FREE ACCOUNT',
    profilePurchasesTitle: 'My purchases',
    profileBenefitsTitle: 'What you get',
    profileBenefitCustomListsLabel: 'Custom word lists',
    profileBenefitCustomListsSub: 'Upload your own words — CSV or plain text',
    profileBenefitWordPacksLabel: '{0} word packs',
    profileBenefitWordPacksLabelZero: 'Word packs',
    profileBenefitWordPacksSub: 'New topics & languages — constantly growing',
    profileBenefitVisualThemesLabel: '{0} visual themes',
    profileBenefitVisualThemesLabelZero: 'Visual themes',
    profileBenefitVisualThemesSub: 'Unique app skins for your style',
    profileBenefitGameStatsLabel: 'Game statistics',
    profileBenefitGameStatsSub: 'Track wins, rounds played & top words',
    profileBenefitSyncLabel: 'Sync across devices',
    profileBenefitSyncSub: 'Your purchases & decks everywhere',
    statsScreenTitle: 'My statistics',
    statsRowGamesPlayed: 'Games played',
    statsRowWordsGuessed: 'Words guessed',
    statsRowWordsSkipped: 'Words skipped',
    statsRowAccuracy: 'Accuracy',
    statsLastPlayedPrefix: 'Last played:',
    statsGuestBannerBody:
      'Sign in to keep your statistics forever and sync them across your devices.',
    statsGuestBannerCta: 'Sign in',
    themeLockedAuthRequired: 'Available only after sign-in',
    loginTitle: 'Sign in',
    loginSubtitleShopping: 'For purchases and saved progress',
    loginSubtitleStats:
      'Keep your game history and statistics in your account and sync across devices.',
    loginAnonymousNote:
      'You can play without signing in — sign in is for purchases and cloud-backed statistics',
    loginGoogle: 'Continue with Google',
    loginGoogleLoading: 'Signing in with Google...',
    loginContinueWithout: 'Continue without signing in',
    loginGoogleFailed: 'Google sign-in failed',
    loginGoogleSuppressed:
      'Browser blocked the Google popup. Please try again or check your browser settings.',
  },
};

export const THEME_CONFIG: Record<AppTheme, ThemeConfig> = {
  [AppTheme.PREMIUM_DARK]: {
    id: AppTheme.PREMIUM_DARK,
    name: 'Midnight Ruby',
    description: 'OLED chocolate-black with pearl text and ruby accents',
    labels: {
      [Language.UA]: {
        name: 'Північний рубін',
        description: 'Глибокий OLED-фон, перлинний текст і рубінові акценти.',
      },
    },
    isFree: true,
    isDark: true,
    preview: { bg: '#0A0809', accent: '#E11D48' },
    tokens: {
      bg: '#0A0809',
      surface: '#141012',
      elevated: '#1F181C',
      border: '#382A31',
      borderSubtle: '#2A2025',
      divider: '#2A2025',
      accent: '#E11D48',
      accentHover: '#F43F5E',
      accentPressed: '#BE123C',
      accentMuted: '#3D1520',
      accentRing: '#F43F5E66',
      surfaceHoverColor: '#281E23',
      fg: '#F4EFF1',
      fgMuted: '#B5A8AE',
      fgMutedOpaque: true,
      fgSubtle: '#82757B',
      fgSubtleOpaque: true,
      fgDisabled: '#594F54',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#FF5252',
    },
    fonts: { heading: "'Playfair Display', serif", body: "'Lato', sans-serif" },
    borderRadius: '9999px',
    bg: 'bg-(--ui-bg)',
    card: 'bg-(--ui-card) border border-(--ui-border) shadow-2xl',
    textMain: 'text-(--ui-fg) font-serif',
    textSecondary: 'text-(--ui-fg-muted) font-sans',
    textAccent: 'text-(--ui-accent) font-sans',
    textGradient: 'text-(--ui-fg) font-serif',
    button:
      'bg-(--ui-accent) text-(--ui-accent-contrast) hover:bg-(--ui-accent-hover) active:bg-(--ui-accent-pressed) font-sans shadow-lg',
    iconColor: 'text-(--ui-fg)',
    progressBar: 'bg-(--ui-accent)',
  },
  // Legacy ID (kept for backward compatibility) — same palette as PREMIUM_DARK.
  [AppTheme.PREMIUM_LIGHT]: {
    id: AppTheme.PREMIUM_LIGHT,
    name: 'Midnight Ruby',
    description: 'OLED chocolate-black with pearl text and ruby accents',
    labels: {
      [Language.UA]: {
        name: 'Північний рубін',
        description: 'Глибокий OLED-фон, перлинний текст і рубінові акценти.',
      },
    },
    isFree: true,
    isDark: true,
    preview: { bg: '#0A0809', accent: '#E11D48' },
    tokens: {
      bg: '#0A0809',
      surface: '#141012',
      elevated: '#1F181C',
      border: '#382A31',
      borderSubtle: '#2A2025',
      divider: '#2A2025',
      accent: '#E11D48',
      accentHover: '#F43F5E',
      accentPressed: '#BE123C',
      accentMuted: '#3D1520',
      accentRing: '#F43F5E66',
      surfaceHoverColor: '#281E23',
      fg: '#F4EFF1',
      fgMuted: '#B5A8AE',
      fgMutedOpaque: true,
      fgSubtle: '#82757B',
      fgSubtleOpaque: true,
      fgDisabled: '#594F54',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#FF5252',
    },
    fonts: { heading: "'Playfair Display', serif", body: "'Lato', sans-serif" },
    borderRadius: '9999px',
    bg: 'bg-(--ui-bg)',
    card: 'bg-(--ui-card) border border-(--ui-border) shadow-2xl',
    textMain: 'text-(--ui-fg) font-serif',
    textSecondary: 'text-(--ui-fg-muted) font-sans',
    textAccent: 'text-(--ui-accent) font-sans',
    textGradient: 'text-(--ui-fg) font-serif',
    button:
      'bg-(--ui-accent) text-(--ui-accent-contrast) hover:bg-(--ui-accent-hover) active:bg-(--ui-accent-pressed) font-sans shadow-lg',
    iconColor: 'text-(--ui-fg)',
    progressBar: 'bg-(--ui-accent)',
  },
  [AppTheme.CYBERPUNK]: {
    id: AppTheme.CYBERPUNK,
    name: 'Earthy Dark',
    description: 'Warm accent on grounded dark surfaces',
    isFree: false,
    isDark: true,
    preview: { bg: '#161616', accent: '#B58863' },
    tokens: {
      bg: '#161616',
      surface: '#0B2E2A',
      border: '#3D4D55',
      accent: '#B58863',
      fgMuted: '#A79E9C',
      fg: '#D3C3B9',
    },
    fonts: { heading: "'Playfair Display', serif", body: "'Lato', sans-serif" },
    borderRadius: '9999px',
    bg: 'bg-(--ui-bg)',
    card: 'bg-(--ui-card) border border-(--ui-border) shadow-2xl',
    textMain: 'text-(--ui-fg) font-serif',
    textSecondary: 'text-(--ui-fg-muted) font-sans',
    textAccent: 'text-(--ui-accent) font-sans',
    textGradient: 'text-(--ui-fg) font-serif',
    button:
      'bg-(--ui-accent) text-(--ui-accent-contrast) hover:bg-(--ui-accent-hover) active:bg-(--ui-accent-pressed) font-sans shadow-lg',
    iconColor: 'text-(--ui-fg)',
    progressBar: 'bg-(--ui-accent)',
  },
  [AppTheme.FOREST]: {
    id: AppTheme.FOREST,
    name: 'Luminous Aero',
    description: 'Cool white surfaces with indigo, cyan and coral accents',
    labels: {
      [Language.UA]: {
        description: 'Світла палітра: прохолодний білий, індиго, морський ціан і коралові акценти.',
      },
      [Language.DE]: {
        description: 'Helles Schema: kühles Weiß, Indigo, Meer-Cyan und Korall-Akzente.',
      },
    },
    isFree: false,
    isDark: false,
    preview: { bg: '#FAFCFF', accent: '#6366F1' },
    tokens: {
      bg: '#FAFCFF',
      surface: '#F1F5F9',
      elevated: '#FFFFFF',
      border: '#E2E8F0',
      divider: '#CBD5E1',
      accent: '#6366F1',
      accentSoft: '#E0E7FF',
      accentAlt: '#06B6D4',
      accentWarm: '#F43F5E',
      accentWarmSoft: '#FFE4E6',
      fg: '#0F172A',
      fgMuted: '#64748B',
      fgSubtle: '#94A3B8',
    },
    fonts: { heading: "'Inter', sans-serif", body: "'Inter', sans-serif" },
    borderRadius: '14px',
    bg: 'bg-(--ui-bg)',
    card: 'bg-(--ui-card) border border-(--ui-border) shadow-lg',
    textMain: 'text-(--ui-fg) font-sans',
    textSecondary: 'text-(--ui-fg-muted) font-sans',
    textAccent: 'text-(--ui-accent) font-sans',
    textGradient: 'text-(--ui-fg) font-sans',
    button:
      'bg-(--ui-accent) text-(--ui-accent-contrast) hover:bg-(--ui-accent-hover) active:bg-(--ui-accent-pressed) font-sans shadow-md',
    iconColor: 'text-(--ui-fg)',
    progressBar: 'bg-(--ui-accent)',
  },
  [AppTheme.SLEEK]: {
    id: AppTheme.SLEEK,
    name: 'Dark Ruby',
    description: 'Wine-dark with ruby accents',
    isFree: false,
    isDark: true,
    preview: { bg: '#1A0B12', accent: '#B44C6A' },
    tokens: {
      bg: '#1A0B12',
      surface: '#2A101A',
      border: '#4A1E2E',
      accent: '#B44C6A',
      fgMuted: '#C9A3AE',
      fg: '#F3E7EA',
    },
    fonts: { heading: "'Playfair Display', serif", body: "'Lato', sans-serif" },
    borderRadius: '9999px',
    bg: 'bg-(--ui-bg)',
    card: 'bg-(--ui-card) border border-(--ui-border) shadow-2xl',
    textMain: 'text-(--ui-fg) font-serif',
    textSecondary: 'text-(--ui-fg-muted) font-sans',
    textAccent: 'text-(--ui-accent) font-sans',
    textGradient: 'text-(--ui-fg) font-serif',
    button:
      'bg-(--ui-accent) text-(--ui-accent-contrast) hover:bg-(--ui-accent-hover) active:bg-(--ui-accent-pressed) font-sans shadow-lg',
    iconColor: 'text-(--ui-fg)',
    progressBar: 'bg-(--ui-accent)',
  },
  [AppTheme.VOID_LUXE]: {
    id: AppTheme.VOID_LUXE,
    name: 'Void Luxe',
    description: 'OLED black with cool blue and warm premium accents',
    isFree: false,
    isDark: true,
    preview: { bg: '#000000', accent: '#052659' },
    tokens: {
      bg: '#000000',
      surface: '#021024',
      elevated: '#06141B',
      border: '#11212D',
      divider: '#253745',
      accent: '#052659',
      accentSoft: '#5483B3',
      accentAlt: '#7DA0CA',
      accentWarm: '#B58863',
      accentWarmSoft: '#D3C3B9',
      fg: '#C1E8FF',
      fgMuted: '#9BA8AB',
      fgSubtle: '#CCD0CF',
    },
    fonts: { heading: "'Playfair Display', serif", body: "'Lato', sans-serif" },
    borderRadius: '9999px',
    bg: 'bg-(--ui-bg)',
    card: 'bg-(--ui-card) border border-(--ui-border) shadow-2xl',
    textMain: 'text-(--ui-fg) font-serif',
    textSecondary: 'text-(--ui-fg-muted) font-sans',
    textAccent: 'text-(--ui-accent) font-sans',
    textGradient: 'text-(--ui-fg) font-serif',
    button:
      'bg-(--ui-accent) text-(--ui-accent-contrast) hover:bg-(--ui-accent-hover) active:bg-(--ui-accent-pressed) font-sans shadow-lg',
    iconColor: 'text-(--ui-fg)',
    progressBar: 'bg-(--ui-accent)',
  },
  [AppTheme.QUANTUM_ECLIPSE]: {
    id: AppTheme.QUANTUM_ECLIPSE,
    name: 'Quantum Eclipse',
    description: 'True OLED black with violet, cyan, and neon orange accents',
    labels: {
      [Language.UA]: {
        description:
          'OLED-чорний, квантовий фіолетовий, кібер-ціан і неоновий помаранч для акцентів.',
      },
      [Language.DE]: {
        description: 'OLED-Schwarz mit violetten, Cyan- und Neonorange-Akzenten.',
      },
    },
    isFree: false,
    isDark: true,
    preview: { bg: '#000000', accent: '#6C47FF' },
    tokens: {
      bg: '#000000',
      surface: '#0A0A0F',
      elevated: '#13141C',
      border: '#1E202B',
      divider: '#2D3040',
      accent: '#6C47FF',
      accentSoft: '#8B6DFF',
      accentAlt: '#00F0FF',
      accentWarm: '#FF8A00',
      accentWarmSoft: '#FFAB40',
      fg: '#F8FAFC',
      fgMuted: '#8B94A3',
      fgSubtle: '#4A5060',
    },
    fonts: { heading: "'Exo 2', sans-serif", body: "'Inter', sans-serif" },
    borderRadius: '12px',
    bg: 'bg-(--ui-bg)',
    card: 'bg-(--ui-card) border border-(--ui-border) shadow-2xl',
    textMain: 'text-(--ui-fg) font-sans',
    textSecondary: 'text-(--ui-fg-muted) font-sans',
    textAccent: 'text-(--ui-accent) font-sans',
    textGradient: 'text-(--ui-fg) font-sans',
    button:
      'bg-(--ui-accent) text-(--ui-accent-contrast) hover:bg-(--ui-accent-hover) active:bg-(--ui-accent-pressed) font-sans shadow-lg',
    iconColor: 'text-(--ui-fg)',
    progressBar: 'bg-(--ui-accent)',
  },
};
