import { Language } from '@movli/shared';
import { AppTheme, type ThemeConfig } from '../types';

export const THEME_CONFIG: Record<AppTheme, ThemeConfig> = {
  [AppTheme.PAPER_LUXE]: {
    id: AppTheme.PAPER_LUXE,
    name: 'Warm Paper',
    description: 'Warm paper background, graphite type, coral accents, editorial geometry',
    labels: {
      [Language.UA]: {
        name: 'Теплий папір',
        description:
          'Теплий приглушений фон, графітовий текст, коралові акценти та геометричні заголовки.',
      },
      [Language.DE]: {
        name: 'Warmes Papier',
        description: 'Warmer Papierhintergrund, Graphit-Text und Korall-Akzente.',
      },
    },
    isFree: true,
    isDark: false,
    preview: { bg: '#E2E3DB', accent: '#EE4239' },
    tokens: {
      bg: '#E2E3DB',
      surface: '#EBECE5',
      elevated: '#FFFFFF',
      border: '#272828',
      accent: '#EE4239',
      fg: '#272828',
    },
    fonts: {
      heading: "'Montserrat', 'Inter', system-ui, sans-serif",
      body: "'Inter', system-ui, sans-serif",
    },
    heading: {
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: '-0.03em',
    },
    borderRadius: '6px',
    bg: 'bg-ui-bg',
    card: 'bg-ui-card border border-ui-border',
    textMain: 'text-ui-fg font-serif',
    textSecondary: 'text-ui-fg-muted font-sans',
    textAccent: 'text-ui-accent font-sans',
    textGradient: 'text-ui-fg font-serif',
    button:
      'bg-ui-accent text-ui-accent-contrast hover:bg-ui-accent-hover active:bg-ui-accent-pressed font-sans',
    iconColor: 'text-ui-fg',
    progressBar: 'bg-ui-accent',
  },
  [AppTheme.PREMIUM_DARK]: {
    id: AppTheme.PREMIUM_DARK,
    name: 'Midnight Ruby',
    description: 'OLED chocolate-black with pearl text and ruby accents',
    labels: {
      [Language.UA]: {
        name: 'Північний рубін',
        description: 'Глибокий OLED-фон, перлинний текст і рубінові акценти.',
      },
    },
    isFree: true,
    isDark: true,
    preview: { bg: '#0A0809', accent: '#E11D48' },
    tokens: {
      bg: '#0A0809',
      surface: '#141012',
      elevated: '#1F181C',
      border: '#382A31',
      accent: '#E11D48',
      fg: '#F4EFF1',
    },
    fonts: { heading: "'Playfair Display', serif", body: "'Inter', system-ui, sans-serif" },
    borderRadius: '9999px',
    bg: 'bg-ui-bg',
    card: 'bg-ui-card border border-ui-border shadow-2xl',
    textMain: 'text-ui-fg font-serif',
    textSecondary: 'text-ui-fg-muted font-sans',
    textAccent: 'text-ui-accent font-sans',
    textGradient: 'text-ui-fg font-serif',
    button:
      'bg-ui-accent text-ui-accent-contrast hover:bg-ui-accent-hover active:bg-ui-accent-pressed font-sans',
    iconColor: 'text-ui-fg',
    progressBar: 'bg-ui-accent',
  },
  // Legacy ID (kept for backward compatibility) — same palette as PREMIUM_DARK.
  [AppTheme.PREMIUM_LIGHT]: {
    id: AppTheme.PREMIUM_LIGHT,
    name: 'Midnight Ruby',
    description: 'OLED chocolate-black with pearl text and ruby accents',
    labels: {
      [Language.UA]: {
        name: 'Північний рубін',
        description: 'Глибокий OLED-фон, перлинний текст і рубінові акценти.',
      },
    },
    isFree: true,
    isDark: true,
    preview: { bg: '#0A0809', accent: '#E11D48' },
    tokens: {
      bg: '#0A0809',
      surface: '#141012',
      elevated: '#1F181C',
      border: '#382A31',
      accent: '#E11D48',
      fg: '#F4EFF1',
    },
    fonts: { heading: "'Playfair Display', serif", body: "'Inter', system-ui, sans-serif" },
    borderRadius: '9999px',
    bg: 'bg-ui-bg',
    card: 'bg-ui-card border border-ui-border shadow-2xl',
    textMain: 'text-ui-fg font-serif',
    textSecondary: 'text-ui-fg-muted font-sans',
    textAccent: 'text-ui-accent font-sans',
    textGradient: 'text-ui-fg font-serif',
    button:
      'bg-ui-accent text-ui-accent-contrast hover:bg-ui-accent-hover active:bg-ui-accent-pressed font-sans',
    iconColor: 'text-ui-fg',
    progressBar: 'bg-ui-accent',
  },
  [AppTheme.CYBERPUNK]: {
    id: AppTheme.CYBERPUNK,
    name: 'Earthy Dark',
    description: 'Warm accent on grounded dark surfaces',
    isFree: false,
    isDark: true,
    preview: { bg: '#161616', accent: '#B58863' },
    tokens: {
      bg: '#161616',
      surface: '#0B2E2A',
      border: '#3D4D55',
      accent: '#B58863',
      fg: '#D3C3B9',
    },
    fonts: { heading: "'Playfair Display', serif", body: "'Inter', system-ui, sans-serif" },
    borderRadius: '9999px',
    bg: 'bg-ui-bg',
    card: 'bg-ui-card border border-ui-border shadow-2xl',
    textMain: 'text-ui-fg font-serif',
    textSecondary: 'text-ui-fg-muted font-sans',
    textAccent: 'text-ui-accent font-sans',
    textGradient: 'text-ui-fg font-serif',
    button:
      'bg-ui-accent text-ui-accent-contrast hover:bg-ui-accent-hover active:bg-ui-accent-pressed font-sans',
    iconColor: 'text-ui-fg',
    progressBar: 'bg-ui-accent',
  },
  [AppTheme.FOREST]: {
    id: AppTheme.FOREST,
    name: 'Luminous Aero',
    description: 'Cool white surfaces with indigo, cyan and coral accents',
    labels: {
      [Language.UA]: {
        description: 'Світла палітра: прохолодний білий, індиго, морський ціан і коралові акценти.',
      },
      [Language.DE]: {
        description: 'Helles Schema: kühles Weiß, Indigo, Meer-Cyan und Korall-Akzente.',
      },
    },
    isFree: false,
    isDark: false,
    preview: { bg: '#FAFCFF', accent: '#6366F1' },
    tokens: {
      bg: '#FAFCFF',
      surface: '#F1F5F9',
      elevated: '#FFFFFF',
      border: '#E2E8F0',
      accent: '#6366F1',
      fg: '#0F172A',
      accentAlt: '#06B6D4',
      accentWarm: '#F43F5E',
    },
    fonts: { heading: "'Inter', sans-serif", body: "'Inter', sans-serif" },
    borderRadius: '14px',
    bg: 'bg-ui-bg',
    card: 'bg-ui-card border border-ui-border shadow-lg',
    textMain: 'text-ui-fg font-sans',
    textSecondary: 'text-ui-fg-muted font-sans',
    textAccent: 'text-ui-accent font-sans',
    textGradient: 'text-ui-fg font-sans',
    button:
      'bg-ui-accent text-ui-accent-contrast hover:bg-ui-accent-hover active:bg-ui-accent-pressed font-sans',
    iconColor: 'text-ui-fg',
    progressBar: 'bg-ui-accent',
  },
  [AppTheme.SLEEK]: {
    id: AppTheme.SLEEK,
    name: 'Dark Ruby',
    description: 'Wine-dark with ruby accents',
    isFree: false,
    isDark: true,
    preview: { bg: '#1A0B12', accent: '#B44C6A' },
    tokens: {
      bg: '#1A0B12',
      surface: '#2A101A',
      border: '#4A1E2E',
      accent: '#B44C6A',
      fg: '#F3E7EA',
    },
    fonts: { heading: "'Playfair Display', serif", body: "'Inter', system-ui, sans-serif" },
    borderRadius: '9999px',
    bg: 'bg-ui-bg',
    card: 'bg-ui-card border border-ui-border shadow-2xl',
    textMain: 'text-ui-fg font-serif',
    textSecondary: 'text-ui-fg-muted font-sans',
    textAccent: 'text-ui-accent font-sans',
    textGradient: 'text-ui-fg font-serif',
    button:
      'bg-ui-accent text-ui-accent-contrast hover:bg-ui-accent-hover active:bg-ui-accent-pressed font-sans',
    iconColor: 'text-ui-fg',
    progressBar: 'bg-ui-accent',
  },
  [AppTheme.VOID_LUXE]: {
    id: AppTheme.VOID_LUXE,
    name: 'Void Luxe',
    description: 'OLED black with cool blue and warm premium accents',
    isFree: false,
    isDark: true,
    preview: { bg: '#000000', accent: '#052659' },
    tokens: {
      bg: '#000000',
      surface: '#021024',
      elevated: '#06141B',
      border: '#11212D',
      accent: '#052659',
      fg: '#C1E8FF',
      accentAlt: '#7DA0CA',
      accentWarm: '#B58863',
    },
    fonts: { heading: "'Playfair Display', serif", body: "'Inter', system-ui, sans-serif" },
    borderRadius: '9999px',
    bg: 'bg-ui-bg',
    card: 'bg-ui-card border border-ui-border shadow-2xl',
    textMain: 'text-ui-fg font-serif',
    textSecondary: 'text-ui-fg-muted font-sans',
    textAccent: 'text-ui-accent font-sans',
    textGradient: 'text-ui-fg font-serif',
    button:
      'bg-ui-accent text-ui-accent-contrast hover:bg-ui-accent-hover active:bg-ui-accent-pressed font-sans',
    iconColor: 'text-ui-fg',
    progressBar: 'bg-ui-accent',
  },
  [AppTheme.QUANTUM_ECLIPSE]: {
    id: AppTheme.QUANTUM_ECLIPSE,
    name: 'Quantum Eclipse',
    description: 'True OLED black with violet, cyan, and neon orange accents',
    labels: {
      [Language.UA]: {
        description:
          'OLED-чорний, квантовий фіолетовий, кібер-ціан і неоновий помаранч для акцентів.',
      },
      [Language.DE]: {
        description: 'OLED-Schwarz mit violetten, Cyan- und Neonorange-Akzenten.',
      },
    },
    isFree: false,
    isDark: true,
    preview: { bg: '#000000', accent: '#6C47FF' },
    tokens: {
      bg: '#000000',
      surface: '#0A0A0F',
      elevated: '#13141C',
      border: '#1E202B',
      accent: '#6C47FF',
      fg: '#F8FAFC',
      accentAlt: '#00F0FF',
      accentWarm: '#FF8A00',
    },
    fonts: { heading: "'Exo 2', sans-serif", body: "'Inter', sans-serif" },
    borderRadius: '12px',
    bg: 'bg-ui-bg',
    card: 'bg-ui-card border border-ui-border shadow-2xl',
    textMain: 'text-ui-fg font-sans',
    textSecondary: 'text-ui-fg-muted font-sans',
    textAccent: 'text-ui-accent font-sans',
    textGradient: 'text-ui-fg font-sans',
    button:
      'bg-ui-accent text-ui-accent-contrast hover:bg-ui-accent-hover active:bg-ui-accent-pressed font-sans',
    iconColor: 'text-ui-fg',
    progressBar: 'bg-ui-accent',
  },
};
